-- Garmin Exercises: PLYO

-- Total exercises: 38

-- Generated: 2025-11-18T02:24:16.089Z


INSERT INTO garmin_exercises (exercise_category, exercise_name, type, tags, equipment, description)
VALUES ('PLYO', 'ALTERNATING_JUMP_LUNGE', 'STRENGTH', '{legs,quads,glutes,lunge pattern,plyometric,explosive,power,cardio}', '{bodyweight}', 'THE classic plyometric lunge - explosively jump and switch legs mid-air. From lunge position, jump explosively, switch legs in flight, land in opposite lunge. This fundamental power exercise builds explosive leg strength, cardiovascular conditioning, and coordination. The rapid leg switching challenges balance and timing. Essential for athletic training across all sports. Excellent for building power endurance and fat burning. One of the most effective plyometric leg exercises.');

INSERT INTO garmin_exercises (exercise_category, exercise_name, type, tags, equipment, description)
VALUES ('PLYO', 'BARBELL_JUMP_SQUAT', 'STRENGTH', '{legs,quads,glutes,squat pattern,plyometric,explosive,power}', '{barbell}', 'Advanced loaded jump squat with barbell - explosive power under resistance. Barbell on back, squat down, explode upward jumping off ground. This advanced plyometric exercise builds maximum lower body power with external load. The barbell adds significant resistance, increasing power output demands. Only for experienced athletes with excellent squat mechanics. Requires careful landing technique to protect knees and back. One of the most effective exercises for building weighted explosive power.');

INSERT INTO garmin_exercises (exercise_category, exercise_name, type, tags, equipment, description)
VALUES ('PLYO', 'BODY_WEIGHT_JUMP_SQUAT', 'STRENGTH', '{legs,quads,glutes,squat pattern,plyometric,explosive,power,cardio}', '{bodyweight}', 'Fundamental bodyweight jump squat - THE foundational plyometric leg exercise. Squat down, explosively jump as high as possible, land softly. This essential power movement builds explosive leg strength, rate of force development, and cardiovascular endurance. The most accessible jump squat variation for all fitness levels. Teaches proper landing mechanics essential for all plyometrics. Excellent for athletic performance, power development, and conditioning. One of the best bodyweight power exercises.');

INSERT INTO garmin_exercises (exercise_category, exercise_name, type, tags, equipment, description)
VALUES ('PLYO', 'BOX_JUMP', 'STRENGTH', '{legs,quads,glutes,plyometric,explosive,power}', '{box}', 'THE iconic box jump - explosively jump from floor onto elevated box. Stand facing box, jump explosively, land softly on top. This fundamental plyometric exercise builds tremendous lower body power and explosiveness. The box provides a clear target and reduces landing impact (step down, don\'t jump down). Essential for athletic training, CrossFit, and power development. Adjustable difficulty via box height. One of the most popular and effective plyometric exercises. Builds confidence and explosive power.');

INSERT INTO garmin_exercises (exercise_category, exercise_name, type, tags, equipment, description)
VALUES ('PLYO', 'BOX_JUMP_OVERS', 'STRENGTH', '{legs,quads,glutes,plyometric,explosive,power,cardio}', '{box}', 'Dynamic box jump variation - jump over the box without landing on top. Jump laterally over box, land on other side, immediately jump back. This continuous plyometric exercise builds lateral power, cardiovascular endurance, and coordination. The side-to-side pattern engages different muscles than forward jumps. Excellent for conditioning and power endurance. Higher intensity than standard box jumps due to continuous jumping. Popular in functional fitness and athletic training.');

INSERT INTO garmin_exercises (exercise_category, exercise_name, type, tags, equipment, description)
VALUES ('PLYO', 'BOX_JUMP_OVERS_OVER_THE_BOX', 'STRENGTH', '{legs,quads,glutes,plyometric,explosive,power,cardio}', '{box}', 'Box jump overs clearing the top - jump over box going fully over the top surface. Jump up and over the box, clearing the top completely, land on opposite side. This challenging variation requires more vertical power than side-to-side box jump overs. The higher trajectory demands greater explosiveness. Excellent for building maximum vertical power and conditioning. More demanding than lateral box jump overs. Builds exceptional explosive strength.');

INSERT INTO garmin_exercises (exercise_category, exercise_name, type, tags, equipment, description)
VALUES ('PLYO', 'CROSS_KNEE_STRIKE', 'STRENGTH', '{core,abs,obliques,hip flexors,plyometric,explosive,power,cardio}', '{bodyweight}', 'Explosive cross-body knee strike - martial arts inspired plyometric exercise. Drive knee across body toward opposite side explosively, rapidly alternate sides. This dynamic movement builds explosive rotational power, oblique strength, and cardiovascular endurance. The cross-body pattern engages core rotation and obliques. Popular in martial arts conditioning, boxing training, and HIIT workouts. Excellent for building power endurance and core conditioning. The rapid alternating builds exceptional work capacity.');

INSERT INTO garmin_exercises (exercise_category, exercise_name, type, tags, equipment, description)
VALUES ('PLYO', 'DEPTH_JUMP', 'STRENGTH', '{legs,quads,glutes,plyometric,explosive,power,reactive}', '{box}', 'Advanced reactive plyometric - step off box, land and immediately explode upward. Step off elevated surface, absorb landing, immediately jump maximally. This elite plyometric exercise builds exceptional reactive strength and elastic power. The depth drop loads muscles eccentrically, then demands immediate concentric explosion. Only for very advanced athletes with excellent landing mechanics. Develops the stretch-shortening cycle. One of the most advanced plyometric exercises. Builds elite-level explosiveness.');

INSERT INTO garmin_exercises (exercise_category, exercise_name, type, tags, equipment, description)
VALUES ('PLYO', 'DUMBBELL_JUMP_SQUAT', 'STRENGTH', '{legs,quads,glutes,squat pattern,plyometric,explosive,power}', '{dumbbells}', 'Loaded jump squat holding dumbbells - explosive power with added resistance. Hold dumbbells at sides, squat down, jump explosively. This weighted plyometric variation builds greater power than bodyweight jumps. The dumbbells allow natural arm movement and easier balance than barbell. Excellent progression toward heavier loaded plyometrics. The added weight increases power output and strength development. Builds explosive strength under load.');

INSERT INTO garmin_exercises (exercise_category, exercise_name, type, tags, equipment, description)
VALUES ('PLYO', 'DUMBBELL_SPLIT_JUMP', 'STRENGTH', '{legs,quads,glutes,lunge pattern,plyometric,explosive,power}', '{dumbbells}', 'Weighted split jump (jump lunge) with dumbbells - loaded explosive lunge variation. Hold dumbbells, perform explosive alternating jump lunges. This weighted plyometric builds exceptional single-leg power and control under load. The dumbbells increase resistance while maintaining natural movement. More challenging than bodyweight jump lunges. Excellent for building weighted explosive strength. The single-leg nature addresses imbalances.');

INSERT INTO garmin_exercises (exercise_category, exercise_name, type, tags, equipment, description)
VALUES ('PLYO', 'FRONT_KNEE_STRIKE', 'STRENGTH', '{core,abs,hip flexors,plyometric,explosive,power,cardio}', '{bodyweight}', 'Explosive front knee drive - martial arts inspired power movement. Drive knee straight up toward chest explosively, rapidly alternate legs. This dynamic exercise builds explosive hip flexor power, core strength, and cardiovascular endurance. The vertical knee drive pattern builds hip flexor explosiveness. Popular in martial arts, boxing, and combat sports conditioning. Excellent for building power endurance and conditioning. The rapid alternating creates intense cardiovascular demand.');

INSERT INTO garmin_exercises (exercise_category, exercise_name, type, tags, equipment, description)
VALUES ('PLYO', 'HIGH_BOX_JUMP', 'STRENGTH', '{legs,quads,glutes,plyometric,explosive,power}', '{box}', 'Maximum height box jump - testing maximum vertical explosive power. Jump onto highest box possible. This challenge variation tests and builds maximum vertical power output. The high box demands maximum explosive effort and confidence. Essential for measuring progress in power development. Requires excellent explosiveness, landing mechanics, and confidence. Builds maximum vertical jumping power. The height challenge pushes explosive limits.');

INSERT INTO garmin_exercises (exercise_category, exercise_name, type, tags, equipment, description)
VALUES ('PLYO', 'ISOMETRIC_EXPLOSIVE_BODY_WEIGHT_JUMP_SQUAT', 'STRENGTH', '{legs,quads,glutes,squat pattern,plyometric,explosive,power,isometric}', '{bodyweight}', 'Jump squat with isometric hold - combining static strength with explosive power. Hold squat position isometrically, then explode into maximum jump. This unique variation combines isometric strength building with plyometric power. The pause eliminates the stretch reflex, requiring pure concentric power. Builds starting strength and explosive power from static positions. The isometric hold increases time under tension. Excellent for breaking through power plateaus.');

INSERT INTO garmin_exercises (exercise_category, exercise_name, type, tags, equipment, description)
VALUES ('PLYO', 'JUMP_SQUAT', 'STRENGTH', '{legs,quads,glutes,squat pattern,plyometric,explosive,power,cardio}', '{bodyweight}', 'Generic jump squat movement - fundamental explosive leg exercise. Squat down and jump explosively. This essential plyometric builds lower body power and explosiveness. Can refer to any jump squat variation. Widely used across all strength and conditioning programs. Builds explosive leg strength and cardiovascular endurance. One of the most effective bodyweight power exercises.');

INSERT INTO garmin_exercises (exercise_category, exercise_name, type, tags, equipment, description)
VALUES ('PLYO', 'LATERAL_LEAP_AND_HOP', 'STRENGTH', '{legs,quads,glutes,hip abductors,plyometric,explosive,power,lateral}', '{bodyweight}', 'Lateral plyometric movement - explosive side-to-side leaping and hopping. Leap laterally to one side, land on one leg, hop, repeat to other side. This multi-directional plyometric builds lateral power, single-leg stability, and coordination. The lateral movement pattern engages hip abductors and adductors. Excellent for sports requiring lateral movement (basketball, tennis, soccer). Builds directional change ability. The single-leg landing challenges balance and control.');

INSERT INTO garmin_exercises (exercise_category, exercise_name, type, tags, equipment, description)
VALUES ('PLYO', 'LATERAL_PLYO_SQUATS', 'STRENGTH', '{legs,quads,glutes,hip abductors,squat pattern,plyometric,explosive,power,lateral}', '{bodyweight}', 'Lateral jumping squat variation - explosive side-to-side squat jumps. Jump laterally from squat, land in squat on other side, immediately jump back. This lateral plyometric builds multi-directional power and hip strength. The side-to-side pattern engages hip abductors and adductors intensely. Excellent for athletic training requiring lateral explosiveness. Builds lateral power and agility. Popular in sports performance training.');

INSERT INTO garmin_exercises (exercise_category, exercise_name, type, tags, equipment, description)
VALUES ('PLYO', 'LATERAL_SLIDE', 'STRENGTH', '{legs,quads,hip abductors,hip adductors,plyometric,power,lateral}', '{sliding discs}', 'Lateral sliding movement on discs - controlled lateral power training. Place one foot on slider, explosively slide to side and back. This controlled plyometric builds lateral power with reduced impact. The sliding motion creates smooth, continuous tension. Excellent for building lateral strength and power with lower joint stress. The discs allow for speed control. Great for injury prevention and lateral power development.');

INSERT INTO garmin_exercises (exercise_category, exercise_name, type, tags, equipment, description)
VALUES ('PLYO', 'MEDICINE_BALL_OVERHEAD_THROWS', 'STRENGTH', '{shoulders,core,abs,back,plyometric,explosive,power}', '{medicine ball}', 'Explosive overhead medicine ball throws - total body power movement. Lift ball overhead and slam down forcefully, or throw against wall. This full-body plyometric builds explosive overhead power and core strength. The overhead throwing motion engages shoulders, core, and back. Excellent for building total body explosiveness. Popular in functional training and athletic conditioning. The catch and throw cycle builds reactive power.');

INSERT INTO garmin_exercises (exercise_category, exercise_name, type, tags, equipment, description)
VALUES ('PLYO', 'MEDICINE_BALL_SIDE_THROW', 'STRENGTH', '{core,abs,obliques,back,plyometric,explosive,power,rotation}', '{medicine ball}', 'Rotational medicine ball throws to the side - explosive rotational power. Rotate and throw ball explosively to side (partner or wall). This rotational plyometric builds exceptional oblique and rotational power. The explosive rotation engages the entire core powerfully. Essential for rotational sports (baseball, golf, tennis). Builds explosive rotational strength and power. The catch and throw develops reactive rotational ability.');

INSERT INTO garmin_exercises (exercise_category, exercise_name, type, tags, equipment, description)
VALUES ('PLYO', 'MEDICINE_BALL_SLAM', 'STRENGTH', '{shoulders,core,abs,back,plyometric,explosive,power,cardio}', '{medicine ball}', 'THE medicine ball slam - explosive total body power and conditioning. Lift ball overhead and slam down with maximum force. This brutally effective exercise builds explosive power, core strength, and cardiovascular endurance. The full-body slam engages everything from shoulders to core. Excellent for power development, stress relief, and conditioning. Popular in functional training and HIIT workouts. One of the most effective medicine ball exercises.');

INSERT INTO garmin_exercises (exercise_category, exercise_name, type, tags, equipment, description)
VALUES ('PLYO', 'SIDE_TO_SIDE_MEDICINE_BALL_THROWS', 'STRENGTH', '{core,abs,obliques,plyometric,explosive,power,rotation}', '{medicine ball}', 'Continuous lateral medicine ball throws - rapid side-to-side rotational power. Throw ball to one side (wall or partner), catch, immediately throw to other side. This dynamic rotational exercise builds explosive oblique power and conditioning. The rapid alternating develops rotational power endurance. Excellent for sports requiring quick directional changes. The continuous throwing creates cardiovascular demand. Builds rotational speed and power.');

INSERT INTO garmin_exercises (exercise_category, exercise_name, type, tags, equipment, description)
VALUES ('PLYO', 'SIDE_TO_SIDE_SHUFFLE_JUMP', 'STRENGTH', '{legs,quads,hip abductors,plyometric,explosive,power,lateral,cardio}', '{bodyweight}', 'Lateral shuffle with explosive jumps - rapid side-to-side plyometric movement. Shuffle laterally with quick steps, explosively jump side-to-side. This dynamic plyometric builds lateral power, agility, and cardiovascular endurance. The shuffle-jump pattern mimics athletic movements. Essential for sports requiring lateral quickness (basketball, tennis, soccer). Builds lateral explosiveness and conditioning. The rapid changes challenge coordination.');

INSERT INTO garmin_exercises (exercise_category, exercise_name, type, tags, equipment, description)
VALUES ('PLYO', 'SQUAT_JUMP_ONTO_BOX', 'STRENGTH', '{legs,quads,glutes,squat pattern,plyometric,explosive,power}', '{box}', 'Box jump from squat position - emphasizing squat depth before explosion. Start in squat, explosively jump onto box. This variation emphasizes the squat component before the jump. The deeper starting position increases power demands. Excellent for building explosive power from deep positions. The squat start eliminates momentum. Builds exceptional starting strength and power.');

INSERT INTO garmin_exercises (exercise_category, exercise_name, type, tags, equipment, description)
VALUES ('PLYO', 'SQUAT_JUMPS_IN_AND_OUT', 'STRENGTH', '{legs,quads,glutes,hip abductors,hip adductors,squat pattern,plyometric,explosive,power,cardio}', '{bodyweight}', 'Jump squat with stance width changes - feet together then apart. Jump with feet together, land in wide squat, jump feet back together. This dynamic variation adds hip abduction/adduction to jump squats. The in-and-out pattern engages inner and outer thighs. Excellent for building multi-planar leg power. The stance changes challenge coordination and hip strength. Builds complete lower body power.');

INSERT INTO garmin_exercises (exercise_category, exercise_name, type, tags, equipment, description)
VALUES ('PLYO', 'STAR_JUMP_SQUATS', 'STRENGTH', '{legs,quads,glutes,shoulders,squat pattern,plyometric,explosive,power,cardio}', '{bodyweight}', 'Explosive star jump from squat - maximum effort total body jump. Squat down, explosively jump spreading arms and legs into star shape. This maximum effort plyometric builds total body explosiveness and power. The star position requires full-body extension and coordination. Excellent for building maximum explosive power and conditioning. The full extension maximizes power output. Popular in HIIT and athletic training.');

INSERT INTO garmin_exercises (exercise_category, exercise_name, type, tags, equipment, description)
VALUES ('PLYO', 'WEIGHTED_ALTERNATING_JUMP_LUNGE', 'STRENGTH', '{legs,quads,glutes,lunge pattern,plyometric,explosive,power}', '{weight vest,dumbbells}', 'Weighted jump lunges - explosive alternating lunges with added resistance. Perform jump lunges while wearing weight vest or holding light dumbbells. This loaded plyometric builds exceptional explosive leg power under resistance. The added weight significantly increases power demands and strength development. Only for athletes with mastered bodyweight jump lunges. Builds elite-level weighted explosive power. The resistance makes each jump more challenging.');

INSERT INTO garmin_exercises (exercise_category, exercise_name, type, tags, equipment, description)
VALUES ('PLYO', 'WEIGHTED_CROSS_KNEE_STRIKE', 'STRENGTH', '{core,abs,obliques,hip flexors,plyometric,explosive,power}', '{weight vest,ankle weights}', 'Weighted cross-body knee strikes - explosive rotational movement with added load. Perform cross knee strikes with weight vest or ankle weights. The added resistance increases rotational power demands and core strength requirements. This loaded variation builds weighted explosive rotational power. The weight makes the movement more challenging for strength and power development. Builds weighted core explosiveness.');

INSERT INTO garmin_exercises (exercise_category, exercise_name, type, tags, equipment, description)
VALUES ('PLYO', 'WEIGHTED_DEPTH_JUMP', 'STRENGTH', '{legs,quads,glutes,plyometric,explosive,power,reactive}', '{weight vest}', 'Advanced weighted depth jump - reactive plyometric with added load. Step off box wearing weight vest, land and immediately explode upward. This elite-level plyometric builds maximum reactive strength under load. The depth drop plus weight creates extreme eccentric loading. Only for very advanced athletes. The weighted landing requires exceptional strength and control. Builds supreme reactive power.');

INSERT INTO garmin_exercises (exercise_category, exercise_name, type, tags, equipment, description)
VALUES ('PLYO', 'WEIGHTED_FRONT_KNEE_STRIKE', 'STRENGTH', '{core,abs,hip flexors,plyometric,explosive,power}', '{weight vest,ankle weights}', 'Weighted front knee drives - explosive vertical knee strikes with added resistance. Drive knees up explosively while wearing vest or ankle weights. The added load significantly increases hip flexor power demands and core engagement. This weighted variation builds exceptional explosive hip flexor strength. The resistance makes each strike more powerful. Builds weighted explosive power.');

INSERT INTO garmin_exercises (exercise_category, exercise_name, type, tags, equipment, description)
VALUES ('PLYO', 'WEIGHTED_HIGH_BOX_JUMP', 'STRENGTH', '{legs,quads,glutes,plyometric,explosive,power}', '{box,weight vest}', 'Maximum height box jump with added weight - ultimate power challenge. Jump onto highest possible box while wearing weight vest. This extreme variation tests maximum weighted explosive power. The high box plus weight creates supreme power demands. Only for elite athletes. Requires exceptional strength, power, and confidence. Builds maximum weighted vertical power.');

INSERT INTO garmin_exercises (exercise_category, exercise_name, type, tags, equipment, description)
VALUES ('PLYO', 'WEIGHTED_ISOMETRIC_EXPLOSIVE_JUMP_SQUAT', 'STRENGTH', '{legs,quads,glutes,squat pattern,plyometric,explosive,power,isometric}', '{weight vest}', 'Weighted isometric jump squat - combining static hold with explosive jump under load. Hold weighted squat isometrically, then explode into maximum jump. This advanced variation combines isometric strength, pure concentric power, and added resistance. The weighted pause eliminates stretch reflex completely. Builds exceptional starting strength and weighted explosive power. Only for advanced athletes. The combination is brutally effective.');

INSERT INTO garmin_exercises (exercise_category, exercise_name, type, tags, equipment, description)
VALUES ('PLYO', 'WEIGHTED_JUMP_SQUAT', 'STRENGTH', '{legs,quads,glutes,squat pattern,plyometric,explosive,power}', '{weight vest}', 'Generic weighted jump squat - fundamental loaded plyometric. Perform jump squats wearing weight vest. This essential weighted plyometric builds explosive leg power under resistance. Can refer to any weighted jump squat variation. The added load increases power output and strength demands. Widely used for building weighted explosiveness. Essential progression for power development.');

INSERT INTO garmin_exercises (exercise_category, exercise_name, type, tags, equipment, description)
VALUES ('PLYO', 'WEIGHTED_LATERAL_LEAP_AND_HOP', 'STRENGTH', '{legs,quads,glutes,hip abductors,plyometric,explosive,power,lateral}', '{weight vest}', 'Weighted lateral leaping and hopping - loaded multi-directional plyometric. Perform lateral leaps and hops while wearing weight vest. This loaded lateral plyometric builds exceptional lateral power under resistance. The weight significantly increases demands on hip abductors and stabilizers. Only for athletes with mastered bodyweight version. Builds elite weighted lateral explosiveness.');

INSERT INTO garmin_exercises (exercise_category, exercise_name, type, tags, equipment, description)
VALUES ('PLYO', 'WEIGHTED_LATERAL_PLYO_SQUATS', 'STRENGTH', '{legs,quads,glutes,hip abductors,squat pattern,plyometric,explosive,power,lateral}', '{weight vest}', 'Weighted lateral jump squats - loaded side-to-side explosive squats. Perform lateral plyo squats wearing weight vest. This loaded lateral variation builds maximum lateral power and hip strength under resistance. The weight dramatically increases power demands. Excellent for building weighted multi-directional explosiveness. The lateral pattern with load is extremely demanding.');

INSERT INTO garmin_exercises (exercise_category, exercise_name, type, tags, equipment, description)
VALUES ('PLYO', 'WEIGHTED_LATERAL_SLIDE', 'STRENGTH', '{legs,quads,hip abductors,hip adductors,plyometric,power,lateral}', '{sliding discs,weight vest}', 'Weighted lateral slides - controlled lateral power with added resistance. Perform lateral slides wearing weight vest. The combination of sliding motion and added weight builds exceptional lateral strength. The weight increases power demands while the slides maintain smooth control. Excellent for weighted lateral power with reduced impact. Builds weighted hip strength and power.');

INSERT INTO garmin_exercises (exercise_category, exercise_name, type, tags, equipment, description)
VALUES ('PLYO', 'WEIGHTED_SIDE_TO_SIDE_SHUFFLE_JUMP', 'STRENGTH', '{legs,quads,hip abductors,plyometric,explosive,power,lateral}', '{weight vest}', 'Weighted shuffle jumps - loaded rapid lateral plyometric movement. Perform shuffle jumps while wearing weight vest. This loaded lateral plyometric builds weighted lateral explosiveness and conditioning. The vest adds significant resistance to the rapid movement. Excellent for building weighted agility and lateral power. The combination is extremely challenging.');

INSERT INTO garmin_exercises (exercise_category, exercise_name, type, tags, equipment, description)
VALUES ('PLYO', 'WEIGHTED_SQUAT_JUMP_ONTO_BOX', 'STRENGTH', '{legs,quads,glutes,squat pattern,plyometric,explosive,power}', '{box,weight vest}', 'Weighted box jump from squat - loaded explosive movement from deep position. Jump onto box from squat position while wearing vest. This loaded variation combines deep squat start with box jump and added weight. The combination creates maximum power demands. Only for very advanced athletes. Builds exceptional weighted explosive power from deep positions.');

INSERT INTO garmin_exercises (exercise_category, exercise_name, type, tags, equipment, description)
VALUES ('PLYO', 'WEIGHTED_SQUAT_JUMPS_IN_AND_OUT', 'STRENGTH', '{legs,quads,glutes,hip abductors,hip adductors,squat pattern,plyometric,explosive,power}', '{weight vest}', 'Weighted in-and-out jump squats - loaded stance-changing plyometric. Perform in-and-out jump squats wearing weight vest. This loaded variation adds resistance to the complex movement pattern. The weight significantly increases demands on all lower body muscles. Builds exceptional weighted multi-planar power. The combination of weight and stance changes is brutally effective.');