-- Garmin Exercises: PULL_UP

-- Total exercises: 46

-- Generated: 2025-11-18T02:24:16.090Z


INSERT INTO garmin_exercises (exercise_category, exercise_name, type, tags, equipment, description)
VALUES ('PULL_UP', '_30_DEGREE_LAT_PULLDOWN', 'STRENGTH', '{back,lats,pull}', '{cable machine}', 'Lat pulldown at 30-degree incline - angled pulling variation. Pull cable down at 30-degree angle from vertical. This angled pulldown variation changes the pulling angle and muscle recruitment pattern. The 30-degree position emphasizes different portions of the lats and back muscles. Excellent for complete lat development from multiple angles. The angle variation prevents adaptation plateaus. Builds back strength from varied pulling angles.');

INSERT INTO garmin_exercises (exercise_category, exercise_name, type, tags, equipment, description)
VALUES ('PULL_UP', 'BAND_ASSISTED_CHIN_UP', 'STRENGTH', '{back,lats,biceps,pull}', '{resistance band,pull-up bar}', 'Band-assisted chin-up - THE best chin-up progression for beginners. Loop resistance band over bar, place knees or feet in band for assistance. This assisted variation allows learning proper chin-up mechanics while building strength. The band provides variable assistance (most at bottom, least at top). Essential progression toward unassisted chin-ups. Allows higher rep ranges for muscle building. Perfect for those working toward their first chin-up.');

INSERT INTO garmin_exercises (exercise_category, exercise_name, type, tags, equipment, description)
VALUES ('PULL_UP', 'BAND_ASSISTED_PULL_UP', 'STRENGTH', '{back,lats,pull}', '{resistance band,pull-up bar}', 'Band-assisted pull-up - THE best pull-up progression tool. Loop band over bar, place knees or feet in band for assistance. This assisted variation makes pull-ups accessible while building strength toward unassisted reps. The band provides graduated assistance throughout the movement. Essential for learning proper pull-up form and building strength. More effective than assisted pull-up machines for carryover. The most popular pull-up progression method.');

INSERT INTO garmin_exercises (exercise_category, exercise_name, type, tags, equipment, description)
VALUES ('PULL_UP', 'BANDED_PULL_UPS', 'STRENGTH', '{back,lats,pull}', '{resistance band,pull-up bar}', 'Pull-ups with resistance band added for extra resistance or assistance. Band can assist (looped for support) or resist (anchored below for added tension). This versatile variation allows for both regression and progression. Bands can add accommodating resistance at top of movement. Excellent for building explosive power or endurance. The variable resistance creates unique training stimulus.');

INSERT INTO garmin_exercises (exercise_category, exercise_name, type, tags, equipment, description)
VALUES ('PULL_UP', 'BURPEE_PULL_UP', 'STRENGTH', '{back,lats,legs,full body,compound,cardio,pull}', '{pull-up bar}', 'THE ultimate conditioning combination - burpee into pull-up. Perform burpee on ground, jump up, immediately do pull-up. This brutally effective exercise combines total body conditioning with pulling strength. The burpee-to-pull-up transition challenges grip and cardiovascular endurance. Popular in CrossFit and military fitness training. Excellent for building work capacity and mental toughness. One of the most challenging bodyweight combinations.');

INSERT INTO garmin_exercises (exercise_category, exercise_name, type, tags, equipment, description)
VALUES ('PULL_UP', 'CHIN_UP', 'STRENGTH', '{back,lats,biceps,pull}', '{pull-up bar}', 'THE classic chin-up - underhand grip pulling movement. Hang from bar with palms facing you, pull chest to bar. This fundamental upper body exercise builds exceptional back and bicep strength. The underhand grip allows more bicep involvement than pull-ups. One of the best bodyweight exercises for upper body pulling strength. Essential for complete back development. More bicep-dominant than pronated pull-ups. A gold standard upper body exercise.');

INSERT INTO garmin_exercises (exercise_category, exercise_name, type, tags, equipment, description)
VALUES ('PULL_UP', 'CLOSE_GRIP_CHIN_UP', 'STRENGTH', '{back,lats,biceps,pull}', '{pull-up bar}', 'Narrow grip chin-up - hands closer together for increased bicep emphasis. Perform chin-up with hands positioned close together (6-8 inches apart). This narrow grip variation emphasizes biceps and inner back muscles more intensely. The close grip increases range of motion and bicep engagement. Excellent for building bicep and lower lat strength. More challenging than standard grip width. Builds peaked biceps and thick lats.');

INSERT INTO garmin_exercises (exercise_category, exercise_name, type, tags, equipment, description)
VALUES ('PULL_UP', 'CLOSE_GRIP_LAT_PULLDOWN', 'STRENGTH', '{back,lats,pull}', '{cable machine}', 'Close grip lat pulldown - narrow grip cable pulling variation. Pull cable down with hands close together. This narrow grip variation emphasizes middle back and lower lats. The close grip allows for deeper contraction and fuller range of motion. Excellent for building lat thickness and middle back development. The vertical pulling path builds lat width and strength. Essential lat-building exercise for back development.');

INSERT INTO garmin_exercises (exercise_category, exercise_name, type, tags, equipment, description)
VALUES ('PULL_UP', 'CROSSOVER_CHIN_UP', 'STRENGTH', '{back,lats,biceps,core,pull}', '{pull-up bar}', 'Alternating crossover chin-up - pull to alternating sides. Pull body toward one side of bar, lower, pull to other side. This asymmetrical variation challenges each side independently and engages obliques. The crossover pattern builds unilateral strength and core stability. Excellent for addressing imbalances and building functional pulling strength. The rotation component adds core work. Advanced chin-up variation.');

INSERT INTO garmin_exercises (exercise_category, exercise_name, type, tags, equipment, description)
VALUES ('PULL_UP', 'EZ_BAR_PULLOVER', 'STRENGTH', '{back,lats,chest,shoulders}', '{ez bar,bench}', 'EZ bar pullover - lying pullover with angled bar. Lie on bench, lower EZ bar overhead in arc, pull back over chest. This isolation exercise targets lats, chest, and serratus. The EZ bar angle reduces wrist strain versus straight bar. Excellent for building lat width and rib cage expansion. The stretching motion builds flexibility and strength. Classic old-school back builder.');

INSERT INTO garmin_exercises (exercise_category, exercise_name, type, tags, equipment, description)
VALUES ('PULL_UP', 'HANGING_HURDLE', 'STRENGTH', '{core,abs,hip flexors,grip}', '{pull-up bar}', 'Hanging hurdle - dynamic hanging leg movement mimicking hurdle clearance. Hang from bar, alternate lifting legs up and over imaginary hurdles. This dynamic core exercise builds hip flexor strength, core control, and grip endurance. The alternating leg movement challenges coordination and obliques. Excellent for building functional core strength and hip mobility. The hanging position demands constant grip and core engagement. Advanced hanging core exercise.');

INSERT INTO garmin_exercises (exercise_category, exercise_name, type, tags, equipment, description)
VALUES ('PULL_UP', 'JUMPING_PULL_UPS', 'STRENGTH', '{back,lats,pull}', '{pull-up bar}', 'Jumping pull-ups - using leg drive to assist pulling movement. Jump to help initiate pull-up, control descent. This regression makes pull-ups accessible for beginners while building strength. The jump provides assistance through the hardest part of the movement. Excellent progression toward unassisted pull-ups. Allows for higher volume training. Good for building pulling strength and mechanics.');

INSERT INTO garmin_exercises (exercise_category, exercise_name, type, tags, equipment, description)
VALUES ('PULL_UP', 'KIPPING_PULL_UP', 'STRENGTH', '{back,lats,core,full body,pull,power}', '{pull-up bar}', 'THE CrossFit kipping pull-up - explosive full-body pulling movement. Use hip drive and body swing to generate momentum for pull-up. This dynamic variation allows higher rep ranges and develops explosive power. The kipping motion engages core and creates full-body coordination. Controversial but effective for conditioning and power development. Essential for CrossFit workouts. Builds different qualities than strict pull-ups. Requires good shoulder mobility.');

INSERT INTO garmin_exercises (exercise_category, exercise_name, type, tags, equipment, description)
VALUES ('PULL_UP', 'KNEELING_LAT_PULLDOWN', 'STRENGTH', '{back,lats,pull}', '{cable machine}', 'Kneeling lat pulldown - performing pulldown from kneeling position. Kneel in front of cable machine, pull bar down to chest. This kneeling variation increases core engagement and reduces momentum. The position forces strict form and full lat contraction. Excellent for building mind-muscle connection with lats. The kneeling stance prevents cheating with leg drive. Builds exceptional lat control and core stability.');

INSERT INTO garmin_exercises (exercise_category, exercise_name, type, tags, equipment, description)
VALUES ('PULL_UP', 'KNEELING_UNDERHAND_GRIP_LAT_PULLDOWN', 'STRENGTH', '{back,lats,biceps,pull}', '{cable machine}', 'Kneeling underhand pulldown - kneeling position with supinated grip. Kneel, pull cable down with underhand grip. This variation combines kneeling stability with underhand grip bicep emphasis. The position maximizes core engagement and lat activation. Excellent for building lower lat and bicep strength with strict form. The underhand grip allows deeper contraction. Builds thick lats and strong biceps.');

INSERT INTO garmin_exercises (exercise_category, exercise_name, type, tags, equipment, description)
VALUES ('PULL_UP', 'L_PULL_UP', 'STRENGTH', '{back,lats,core,abs,hip flexors,pull}', '{pull-up bar}', 'L-sit pull-up - THE ultimate pull-up challenge combining pulling and core strength. Hold L-sit position (legs straight out) while performing pull-ups. This brutally difficult variation requires exceptional core strength, hip flexor endurance, and pulling power simultaneously. The L-sit position dramatically increases demands on abs and hip flexors. Only for very advanced athletes. One of the most difficult pull-up variations. Builds extraordinary total body control.');

INSERT INTO garmin_exercises (exercise_category, exercise_name, type, tags, equipment, description)
VALUES ('PULL_UP', 'LAT_PULLDOWN', 'STRENGTH', '{back,lats,pull}', '{cable machine}', 'THE fundamental lat pulldown - essential cable back exercise. Sit at lat pulldown machine, pull bar down to chest level. This foundational exercise builds lat width and back thickness. More accessible than pull-ups for beginners while allowing progressive overload. The cable provides constant tension throughout movement. Essential for complete back development. One of the most popular back exercises. Excellent for building v-taper physique.');

INSERT INTO garmin_exercises (exercise_category, exercise_name, type, tags, equipment, description)
VALUES ('PULL_UP', 'MIXED_GRIP_CHIN_UP', 'STRENGTH', '{back,lats,biceps,pull}', '{pull-up bar}', 'Mixed grip chin-up - one hand supinated, one pronated. Perform chin-up with asymmetrical hand positions. This unique variation creates different demands on each side of the body. Excellent for addressing imbalances and building unilateral strength. The mixed grip changes muscle recruitment patterns. Rotate grips between sets for balanced development. Advanced variation for experienced athletes.');

INSERT INTO garmin_exercises (exercise_category, exercise_name, type, tags, equipment, description)
VALUES ('PULL_UP', 'MIXED_GRIP_PULL_UP', 'STRENGTH', '{back,lats,pull}', '{pull-up bar}', 'Mixed grip pull-up - one hand over, one hand under the bar. Perform pull-up with alternating grip positions. This asymmetrical variation builds unilateral strength and addresses imbalances. The mixed grip challenges core stability and coordination. Popular in powerlifting and functional training. Alternate hand positions between sets. Builds exceptional grip strength and pulling power.');

INSERT INTO garmin_exercises (exercise_category, exercise_name, type, tags, equipment, description)
VALUES ('PULL_UP', 'NEUTRAL_GRIP_CHIN_UP', 'STRENGTH', '{back,lats,biceps,pull}', '{pull-up bar}', 'Neutral grip chin-up - palms facing each other on parallel bars. Use parallel grip handles, pull up. This neutral hand position is most natural and comfortable for shoulders. The grip reduces wrist and elbow strain while still emphasizing biceps. Excellent for building pulling strength with joint-friendly positioning. Often easier than standard grips for beginners. Builds strong biceps and thick lats.');

INSERT INTO garmin_exercises (exercise_category, exercise_name, type, tags, equipment, description)
VALUES ('PULL_UP', 'NEUTRAL_GRIP_PULL_UP', 'STRENGTH', '{back,lats,pull}', '{pull-up bar}', 'Neutral grip pull-up - parallel grip pulling movement. Use neutral grip handles (palms facing), perform pull-ups. This shoulder-friendly variation reduces joint stress while building back strength. The neutral position allows many people to perform more reps. Excellent for building lat width and thickness with reduced shoulder strain. The most comfortable grip position for many athletes. Builds exceptional pulling strength.');

INSERT INTO garmin_exercises (exercise_category, exercise_name, type, tags, equipment, description)
VALUES ('PULL_UP', 'PULL_UP', 'STRENGTH', '{back,lats,pull}', '{pull-up bar}', 'THE pull-up - the king of upper body exercises. Hang from bar with overhand grip, pull chin over bar. This fundamental bodyweight exercise builds exceptional back, lat, and grip strength. One of the most important upper body exercises in all of fitness. Essential for complete back development and functional strength. The gold standard for measuring upper body pulling strength. A cornerstone exercise for any training program.');

INSERT INTO garmin_exercises (exercise_category, exercise_name, type, tags, equipment, description)
VALUES ('PULL_UP', 'REVERSE_GRIP_PULLDOWN', 'STRENGTH', '{back,lats,biceps,pull}', '{cable machine}', 'Reverse grip (underhand) lat pulldown - supinated grip cable variation. Pull cable down with palms facing you. This underhand grip variation emphasizes lower lats and biceps significantly. The supinated position allows for deeper contraction and fuller range of motion. Excellent for building bicep and lower lat thickness. The reverse grip is often more comfortable than overhand. Builds exceptional lower lat development and bicep strength.');

INSERT INTO garmin_exercises (exercise_category, exercise_name, type, tags, equipment, description)
VALUES ('PULL_UP', 'STANDING_CABLE_PULLOVER', 'STRENGTH', '{back,lats,core}', '{cable machine}', 'Standing cable pullover - vertical pulling motion from standing position. Stand facing cable machine, pull cable down in arc from overhead to hips. This standing variation builds lat width while engaging core for stability. The vertical position allows for full lat stretch and contraction. Excellent for building lat development and posture. The standing stance increases core engagement. Builds lats and serratus simultaneously.');

INSERT INTO garmin_exercises (exercise_category, exercise_name, type, tags, equipment, description)
VALUES ('PULL_UP', 'STRAIGHT_ARM_PULLDOWN', 'STRENGTH', '{back,lats}', '{cable machine}', 'Straight arm pulldown - isolation exercise for lats with locked elbows. Stand at cable machine, pull bar down with straight arms. This isolation movement targets lats directly without bicep involvement. The straight arm position provides intense lat activation and stretch. Excellent for building lat width and mind-muscle connection. The movement teaches proper lat engagement. Popular finisher exercise for back training.');

INSERT INTO garmin_exercises (exercise_category, exercise_name, type, tags, equipment, description)
VALUES ('PULL_UP', 'SUSPENDED_CHIN_UP', 'STRENGTH', '{back,lats,biceps,core,pull}', '{suspension trainer}', 'Suspension trainer chin-up - underhand grip pulling on unstable straps. Perform chin-ups using suspension trainer handles. This unstable variation increases core engagement and stabilizer demands. The moving handles challenge balance and coordination. Excellent for building functional pulling strength. The instability requires constant core control. More accessible angle than bar chin-ups for beginners.');

INSERT INTO garmin_exercises (exercise_category, exercise_name, type, tags, equipment, description)
VALUES ('PULL_UP', 'SWISS_BALL_EZ_BAR_PULLOVER', 'STRENGTH', '{back,lats,chest,shoulders,core}', '{swiss ball,ez bar}', 'EZ bar pullover on swiss ball - combining instability with pulling movement. Lie upper back on swiss ball, perform EZ bar pullover. This unstable variation increases core engagement throughout the pullover motion. The ball adds balance challenge to the classic lat builder. Excellent for building lats while developing core stability. The instability requires constant micro-adjustments. Advanced pullover variation.');

INSERT INTO garmin_exercises (exercise_category, exercise_name, type, tags, equipment, description)
VALUES ('PULL_UP', 'TOWEL_PULL_UP', 'STRENGTH', '{back,lats,grip,forearms,pull}', '{towels,pull-up bar}', 'Towel pull-up - THE ultimate grip strengthener. Drape towels over bar, grip towels, perform pull-ups. This brutally difficult variation builds exceptional grip and forearm strength. The thick, unstable grip dramatically increases difficulty. Essential for building crushing grip strength. Popular in martial arts and combat sports training. The grip challenge often limits reps before back fatigue. Builds elite-level forearm and grip strength.');

INSERT INTO garmin_exercises (exercise_category, exercise_name, type, tags, equipment, description)
VALUES ('PULL_UP', 'WEIGHTED_BURPEE_PULL_UP', 'STRENGTH', '{back,lats,legs,full body,compound,cardio,pull}', '{weight vest,pull-up bar}', 'Weighted burpee pull-up - THE ultimate conditioning challenge with added resistance. Perform burpee, jump to bar, do weighted pull-up. This extreme variation combines total body conditioning with weighted pulling strength. The vest adds significant resistance to an already brutal movement. Only for elite athletes. Builds extraordinary work capacity, strength, and mental toughness. The ultimate test of fitness.');

INSERT INTO garmin_exercises (exercise_category, exercise_name, type, tags, equipment, description)
VALUES ('PULL_UP', 'WEIGHTED_CHIN_UP', 'STRENGTH', '{back,lats,biceps,pull}', '{weight plates,weight vest,dip belt,pull-up bar}', 'Weighted chin-up - adding external resistance to chin-ups for maximum strength. Attach weight via belt, vest, or hold dumbbell between feet. This fundamental weighted variation builds maximum pulling strength and muscle mass. The added resistance creates progressive overload beyond bodyweight. Essential for advanced back and bicep development. The gold standard weighted pulling exercise. Builds exceptional upper body strength.');

INSERT INTO garmin_exercises (exercise_category, exercise_name, type, tags, equipment, description)
VALUES ('PULL_UP', 'WEIGHTED_CLOSE_GRIP_CHIN_UP', 'STRENGTH', '{back,lats,biceps,pull}', '{weight plates,weight vest,dip belt,pull-up bar}', 'Weighted close grip chin-up - narrow grip with added resistance for intense bicep work. Perform close grip chin-up with weight attached. This loaded variation builds exceptional bicep and inner back strength. The narrow grip plus weight creates maximum bicep engagement. Excellent for building bicep peak and lat thickness. The combination is brutally effective. Builds peaked biceps and powerful lats.');

INSERT INTO garmin_exercises (exercise_category, exercise_name, type, tags, equipment, description)
VALUES ('PULL_UP', 'WEIGHTED_CROSSOVER_CHIN_UP', 'STRENGTH', '{back,lats,biceps,core,pull}', '{weight plates,weight vest,dip belt,pull-up bar}', 'Weighted crossover chin-up - alternating sides with added resistance. Pull to alternating sides while wearing weight. This advanced loaded variation builds unilateral strength and core stability under load. The weight increases the asymmetrical challenge. Only for very advanced athletes. Builds exceptional weighted pulling strength and core control.');

INSERT INTO garmin_exercises (exercise_category, exercise_name, type, tags, equipment, description)
VALUES ('PULL_UP', 'WEIGHTED_HANGING_HURDLE', 'STRENGTH', '{core,abs,hip flexors,grip}', '{weight vest,ankle weights,pull-up bar}', 'Weighted hanging hurdle - dynamic hanging core work with added resistance. Perform hanging hurdles while wearing vest or ankle weights. This loaded variation dramatically increases core and hip flexor demands. The added weight makes the already challenging movement brutally difficult. Builds exceptional weighted core control and grip endurance. Elite-level hanging core exercise.');

INSERT INTO garmin_exercises (exercise_category, exercise_name, type, tags, equipment, description)
VALUES ('PULL_UP', 'WEIGHTED_JUMPING_PULL_UPS', 'STRENGTH', '{back,lats,pull}', '{weight vest,pull-up bar}', 'Weighted jumping pull-ups - jump-assisted pull-ups with added load. Use leg drive to assist weighted pull-ups. This unique variation adds resistance while maintaining assistance from legs. Excellent progression toward full weighted pull-ups. The combination builds explosive power and strength. Good for building weighted pulling strength with volume.');

INSERT INTO garmin_exercises (exercise_category, exercise_name, type, tags, equipment, description)
VALUES ('PULL_UP', 'WEIGHTED_KIPPING_PULL_UP', 'STRENGTH', '{back,lats,core,full body,pull,power}', '{weight vest,pull-up bar}', 'Weighted kipping pull-up - dynamic pulling with added resistance. Perform kipping pull-ups while wearing weight vest. This loaded variation increases the power and strength demands of kipping pull-ups. The weight makes the explosive movement significantly more challenging. Popular in advanced CrossFit training. Builds weighted explosive pulling power. Only for very experienced athletes.');

INSERT INTO garmin_exercises (exercise_category, exercise_name, type, tags, equipment, description)
VALUES ('PULL_UP', 'WEIGHTED_L_PULL_UP', 'STRENGTH', '{back,lats,core,abs,hip flexors,pull}', '{weight plates,weight vest,dip belt,pull-up bar}', 'Weighted L-sit pull-up - THE supreme weighted pull-up challenge. Hold L-sit position while performing weighted pull-ups. This extreme variation combines L-sit core demands with weighted pulling strength. Only for elite-level athletes. Requires extraordinary core strength, hip flexor endurance, and weighted pulling power. The ultimate upper body and core exercise. Builds supreme total body control and strength.');

INSERT INTO garmin_exercises (exercise_category, exercise_name, type, tags, equipment, description)
VALUES ('PULL_UP', 'WEIGHTED_MIXED_GRIP_CHIN_UP', 'STRENGTH', '{back,lats,biceps,pull}', '{weight plates,weight vest,dip belt,pull-up bar}', 'Weighted mixed grip chin-up - asymmetric grip with added resistance. Perform mixed grip chin-up with weight attached. This loaded variation builds unilateral strength under challenging conditions. The mixed grip plus weight creates unique demands. Excellent for building grip strength and addressing imbalances. Rotate grip sides between sets. Advanced weighted variation.');

INSERT INTO garmin_exercises (exercise_category, exercise_name, type, tags, equipment, description)
VALUES ('PULL_UP', 'WEIGHTED_MIXED_GRIP_PULL_UP', 'STRENGTH', '{back,lats,pull}', '{weight plates,weight vest,dip belt,pull-up bar}', 'Weighted mixed grip pull-up - alternating hand positions with added load. Perform mixed grip pull-up with weight. This asymmetrical loaded variation builds exceptional unilateral pulling strength. The mixed grip plus weight challenges grip and core stability. Excellent for powerlifting and functional strength. The combination is extremely demanding. Builds extraordinary weighted pulling power.');

INSERT INTO garmin_exercises (exercise_category, exercise_name, type, tags, equipment, description)
VALUES ('PULL_UP', 'WEIGHTED_NEUTRAL_GRIP_CHIN_UP', 'STRENGTH', '{back,lats,biceps,pull}', '{weight plates,weight vest,dip belt,pull-up bar}', 'Weighted neutral grip chin-up - shoulder-friendly grip with added resistance. Perform parallel grip chin-up with weight attached. This joint-friendly loaded variation builds biceps and lats with minimal shoulder stress. The neutral position allows heavy loading safely. Excellent for building mass with reduced joint strain. Many athletes can handle more weight with neutral grip. Builds powerful biceps and thick lats.');

INSERT INTO garmin_exercises (exercise_category, exercise_name, type, tags, equipment, description)
VALUES ('PULL_UP', 'WEIGHTED_NEUTRAL_GRIP_PULL_UP', 'STRENGTH', '{back,lats,pull}', '{weight plates,weight vest,dip belt,pull-up bar}', 'Weighted neutral grip pull-up - parallel grip with added load for comfortable heavy pulling. Perform neutral grip pull-up with weight. This shoulder-friendly loaded variation allows maximum weight with reduced joint stress. The neutral position is most comfortable for heavy weighted pull-ups. Excellent for building maximum back strength safely. The preferred grip for many strength athletes. Builds exceptional lat development.');

INSERT INTO garmin_exercises (exercise_category, exercise_name, type, tags, equipment, description)
VALUES ('PULL_UP', 'WEIGHTED_PULL_UP', 'STRENGTH', '{back,lats,pull}', '{weight plates,weight vest,dip belt,pull-up bar}', 'THE weighted pull-up - fundamental loaded pulling exercise for maximum back strength. Attach weight via belt, vest, or dumbbell and perform pull-ups. This essential weighted variation builds maximum lat and back strength. The added resistance creates progressive overload for continuous gains. One of the best exercises for building back mass and strength. Essential for advanced back development. The gold standard weighted back exercise.');

INSERT INTO garmin_exercises (exercise_category, exercise_name, type, tags, equipment, description)
VALUES ('PULL_UP', 'WEIGHTED_SUSPENDED_CHIN_UP', 'STRENGTH', '{back,lats,biceps,core,pull}', '{suspension trainer,weight vest}', 'Weighted suspension chin-up - unstable pulling with added resistance. Perform suspension chin-up while wearing weight vest. This loaded unstable variation combines instability with added resistance. The moving handles plus weight create exceptional core and stabilizer demands. Advanced variation for building weighted functional strength. The combination is extremely challenging. Builds weighted pulling power with core stability.');

INSERT INTO garmin_exercises (exercise_category, exercise_name, type, tags, equipment, description)
VALUES ('PULL_UP', 'WEIGHTED_TOWEL_PULL_UP', 'STRENGTH', '{back,lats,grip,forearms,pull}', '{towels,weight plates,weight vest,dip belt,pull-up bar}', 'Weighted towel pull-up - THE ultimate grip and back strengthener. Perform towel pull-ups with weight attached. This extreme variation combines brutal grip demands with weighted pulling. Only for elite athletes with exceptional grip and pulling strength. The thick grip plus weight creates supreme forearm and back demands. Builds crushing grip and powerful back. The most challenging pull-up variation.');

INSERT INTO garmin_exercises (exercise_category, exercise_name, type, tags, equipment, description)
VALUES ('PULL_UP', 'WEIGHTED_WIDE_GRIP_PULL_UP', 'STRENGTH', '{back,lats,pull}', '{weight plates,weight vest,dip belt,pull-up bar}', 'Weighted wide grip pull-up - wide hand position with added load for maximum lat width. Perform wide grip pull-up with weight attached. This loaded variation builds exceptional lat width and upper back thickness. The wide grip plus weight creates maximum lat development. Essential for building impressive back width. The combination is brutally effective for lat growth. Builds the classic wide back V-taper.');

INSERT INTO garmin_exercises (exercise_category, exercise_name, type, tags, equipment, description)
VALUES ('PULL_UP', 'WIDE_GRIP_LAT_PULLDOWN', 'STRENGTH', '{back,lats,pull}', '{cable machine}', 'Wide grip lat pulldown - classic wide hand position for lat width. Pull cable down with hands positioned wide. This fundamental variation builds exceptional lat width and upper back development. The wide grip emphasizes outer lats for v-taper physique. One of the most popular back exercises in bodybuilding. Essential for building back width. The wide position creates maximum lat stretch. Classic lat-building exercise.');

INSERT INTO garmin_exercises (exercise_category, exercise_name, type, tags, equipment, description)
VALUES ('PULL_UP', 'WIDE_GRIP_PULL_UP', 'STRENGTH', '{back,lats,pull}', '{pull-up bar}', 'Wide grip pull-up - hands positioned wide for maximum lat width development. Perform pull-ups with hands significantly wider than shoulders. This fundamental variation emphasizes lat width and upper back thickness. The wide grip creates maximum lat stretch and engagement. Essential for building classic v-taper back. More challenging than standard grip due to leverage. Builds impressive back width and strength.');