-- Garmin Exercises: OLYMPIC_LIFT

-- Total exercises: 28

-- Generated: 2025-11-18T02:24:16.086Z


INSERT INTO garmin_exercises (exercise_category, exercise_name, type, tags, equipment, description)
VALUES ('OLYMPIC_LIFT', 'BARBELL_HANG_POWER_CLEAN', 'STRENGTH', '{legs,back,shoulders,olympic lift,power,explosive,triple extension}', '{barbell}', 'Power clean from hang position (bar at mid-thigh). Explosively pull bar to shoulders, catching in quarter squat. This Olympic lift variation builds exceptional power and rate of force development. The hang position removes the first pull, emphasizing the explosive second pull. Essential for athletic power development. Easier to learn than full clean. Widely used in strength and conditioning programs.');

INSERT INTO garmin_exercises (exercise_category, exercise_name, type, tags, equipment, description)
VALUES ('OLYMPIC_LIFT', 'BARBELL_HANG_POWER_SNATCH', 'STRENGTH', '{legs,back,shoulders,olympic lift,power,explosive,triple extension}', '{barbell}', 'Power snatch from hang position - explosively pull to overhead in wide grip. This advanced Olympic movement builds total body power and speed. The hang position emphasizes explosive hip extension. Requires excellent mobility, timing, and coordination. The wide grip demands exceptional shoulder mobility. Elite power development exercise.');

INSERT INTO garmin_exercises (exercise_category, exercise_name, type, tags, equipment, description)
VALUES ('OLYMPIC_LIFT', 'BARBELL_HANG_PULL', 'STRENGTH', '{legs,back,traps,pull,olympic lift,power,explosive,triple extension}', '{barbell}', 'Explosive pulling movement from hang - pull bar high without catching. This Olympic lift derivative builds pulling power without the technical catch. The movement emphasizes aggressive triple extension (ankle, knee, hip). Excellent for developing power and teaching the pull portion. Safer alternative to full lifts while building explosive strength. Popular accessory exercise.');

INSERT INTO garmin_exercises (exercise_category, exercise_name, type, tags, equipment, description)
VALUES ('OLYMPIC_LIFT', 'BARBELL_HANG_SQUAT_CLEAN', 'STRENGTH', '{legs,back,shoulders,squat pattern,olympic lift,power,explosive,triple extension}', '{barbell}', 'Full clean from hang position - explosively pull and catch in full squat. This technical Olympic lift builds maximum power and strength. The deep catch position requires excellent mobility and core strength. Combines explosive power with deep squat strength. More technically demanding than power clean. Essential for Olympic weightlifting and athletic development.');

INSERT INTO garmin_exercises (exercise_category, exercise_name, type, tags, equipment, description)
VALUES ('OLYMPIC_LIFT', 'BARBELL_HIGH_PULL', 'STRENGTH', '{legs,back,traps,shoulders,pull,olympic lift,power,explosive,triple extension}', '{barbell}', 'Explosively pull barbell to chest height - bar travels vertically with elbows high. This power development exercise emphasizes aggressive upward pull. The high pull builds tremendous trapezius and upper back power. Essential accessory for Olympic lifts. Teaches proper pulling mechanics and triple extension. Excellent for athletic power without technical catching requirements.');

INSERT INTO garmin_exercises (exercise_category, exercise_name, type, tags, equipment, description)
VALUES ('OLYMPIC_LIFT', 'BARBELL_POWER_CLEAN', 'STRENGTH', '{legs,back,shoulders,olympic lift,power,explosive,triple extension}', '{barbell}', 'THE power clean - explosively pull barbell from floor to shoulders, catching in quarter squat. This foundational Olympic lift builds total body explosive power. Essential exercise for athletic performance across all sports. Develops rate of force development, coordination, and full-body power. Easier to learn than full clean. One of the best exercises for building explosive strength.');

INSERT INTO garmin_exercises (exercise_category, exercise_name, type, tags, equipment, description)
VALUES ('OLYMPIC_LIFT', 'BARBELL_POWER_SNATCH', 'STRENGTH', '{legs,back,shoulders,olympic lift,power,explosive,triple extension}', '{barbell}', 'Full power snatch from floor - explosive lift to overhead in wide grip, catching in quarter squat. This technically demanding Olympic lift builds maximum power and total body coordination. The wide grip requires exceptional mobility and speed. The most technical of power movements. Elite athletic development exercise. Builds explosive power like no other lift.');

INSERT INTO garmin_exercises (exercise_category, exercise_name, type, tags, equipment, description)
VALUES ('OLYMPIC_LIFT', 'BARBELL_SNATCH', 'STRENGTH', '{legs,back,shoulders,squat pattern,olympic lift,power,explosive,triple extension}', '{barbell}', 'The full Olympic snatch - explosively lift barbell from floor to overhead, catching in deep squat. One of two Olympic competition lifts. This movement requires maximum power, mobility, speed, and technical precision. The pinnacle of weightlifting movements. Builds exceptional total body power and athleticism. Requires extensive coaching and practice to master.');

INSERT INTO garmin_exercises (exercise_category, exercise_name, type, tags, equipment, description)
VALUES ('OLYMPIC_LIFT', 'BARBELL_SPLIT_JERK', 'STRENGTH', '{legs,shoulders,olympic lift,power,explosive}', '{barbell}', 'Drive barbell overhead from shoulders, splitting legs front and back. The split position allows for heavier weights than push jerk. This technical overhead movement builds explosive pressing power. The split stance provides stability for maximum loads. Essential component of clean and jerk. Requires timing, speed, and coordination. Most common jerk variation in Olympic weightlifting.');

INSERT INTO garmin_exercises (exercise_category, exercise_name, type, tags, equipment, description)
VALUES ('OLYMPIC_LIFT', 'BARBELL_SQUAT_CLEAN', 'STRENGTH', '{legs,back,shoulders,squat pattern,olympic lift,power,explosive,triple extension}', '{barbell}', 'Full clean from floor - explosive pull, catching in full front squat. The first half of clean and jerk, one of two Olympic competition lifts. This technically demanding movement builds maximum power and leg strength. The deep catch requires excellent mobility and core strength. Essential for Olympic weightlifting. Combines explosive power with squat strength. One of the most effective total body exercises.');

INSERT INTO garmin_exercises (exercise_category, exercise_name, type, tags, equipment, description)
VALUES ('OLYMPIC_LIFT', 'CLEAN', 'STRENGTH', '{legs,back,shoulders,olympic lift,power,explosive,triple extension}', '{barbell}', 'Generic clean movement - explosive pull from floor to shoulders. This fundamental Olympic lift variation builds total body power and athleticism. The clean movement pattern is essential for power development. Can refer to power clean or squat clean. Widely used across all strength and conditioning programs. Builds explosive strength and coordination.');

INSERT INTO garmin_exercises (exercise_category, exercise_name, type, tags, equipment, description)
VALUES ('OLYMPIC_LIFT', 'CLEAN_AND_JERK', 'STRENGTH', '{legs,back,shoulders,olympic lift,power,explosive,triple extension}', '{barbell}', 'THE Olympic lift - clean barbell to shoulders, then jerk overhead. One of two Olympic competition lifts. This complete movement combines pulling power, squatting strength, and overhead pressing power. The ultimate test of total body strength and power. Essential for Olympic weightlifting. Builds exceptional athleticism and full-body power. The most complete strength exercise.');

INSERT INTO garmin_exercises (exercise_category, exercise_name, type, tags, equipment, description)
VALUES ('OLYMPIC_LIFT', 'CLEAN_AND_PRESS', 'STRENGTH', '{legs,back,shoulders,push,olympic lift,power,explosive}', '{barbell}', 'Clean to shoulders, then strict press overhead (no leg drive). This old-school Olympic lift was removed from competition in 1972. The strict press component builds pure shoulder strength. Combines explosive clean with strength press. Excellent for building total body strength and pressing power. Still widely used in strength training despite removal from Olympic competition.');

INSERT INTO garmin_exercises (exercise_category, exercise_name, type, tags, equipment, description)
VALUES ('OLYMPIC_LIFT', 'DUMBBELL_CLEAN', 'STRENGTH', '{legs,back,shoulders,olympic lift,power,explosive}', '{dumbbells}', 'Explosive pull of dumbbells from floor to shoulders. The dumbbell version allows for independent arm movement and natural catching position. This variation is easier on wrists than barbell clean. Excellent for building unilateral power and addressing imbalances. The dumbbells allow for more natural movement patterns. Great alternative to barbell cleans.');

INSERT INTO garmin_exercises (exercise_category, exercise_name, type, tags, equipment, description)
VALUES ('OLYMPIC_LIFT', 'DUMBBELL_HANG_PULL', 'STRENGTH', '{legs,back,traps,pull,olympic lift,power,explosive}', '{dumbbells}', 'Explosive dumbbell pull from hang position. The dumbbells allow independent arm movement and natural pulling path. This power development exercise builds explosive strength without complex catching. Excellent for athletic power and upper back development. The hang position emphasizes hip extension power. Great accessory for power development.');

INSERT INTO garmin_exercises (exercise_category, exercise_name, type, tags, equipment, description)
VALUES ('OLYMPIC_LIFT', 'DUMBBELL_HANG_SNATCH', 'STRENGTH', '{legs,back,shoulders,olympic lift,power,explosive}', '{dumbbells}', 'Explosive dumbbell snatch from hang position - pull to overhead in one motion. The dumbbells allow for independent arm movement and natural overhead position. This variation is easier on wrists and shoulders than barbell snatch. The hang position emphasizes explosive hip extension and power. Excellent for building unilateral power and coordination. Great alternative for those with mobility limitations or equipment constraints.');

INSERT INTO garmin_exercises (exercise_category, exercise_name, type, tags, equipment, description)
VALUES ('OLYMPIC_LIFT', 'DUMBBELL_POWER_CLEAN_AND_JERK', 'STRENGTH', '{legs,back,shoulders,olympic lift,power,explosive,triple extension}', '{dumbbells}', 'Complete dumbbell Olympic lift - explosive clean to shoulders, then jerk overhead. The dumbbell version allows independent arm movement throughout both phases. This full movement combines pulling power, catching, and overhead pressing. Excellent for building total body power and coordination with more natural movement patterns than barbell. The dumbbells reduce wrist and shoulder stress. Great alternative to barbell clean and jerk.');

INSERT INTO garmin_exercises (exercise_category, exercise_name, type, tags, equipment, description)
VALUES ('OLYMPIC_LIFT', 'DUMBBELL_POWER_CLEAN_AND_PUSH_PRESS', 'STRENGTH', '{legs,back,shoulders,push,olympic lift,power,explosive,triple extension}', '{dumbbells}', 'Dumbbell power clean followed by push press - combining explosive pull with leg-drive pressing. Clean dumbbells to shoulders explosively, then use leg dip and drive to press overhead. This compound movement builds total body power and pressing strength. The push press allows heavier loads than strict press. Excellent for developing explosive overhead strength. The dumbbell version allows natural movement patterns and independent arm action.');

INSERT INTO garmin_exercises (exercise_category, exercise_name, type, tags, equipment, description)
VALUES ('OLYMPIC_LIFT', 'DUMBBELL_POWER_CLEAN_AND_STRICT_PRESS', 'STRENGTH', '{legs,back,shoulders,push,olympic lift,power,explosive}', '{dumbbells}', 'Dumbbell power clean followed by strict overhead press - no leg drive. Clean dumbbells explosively to shoulders, then press overhead using pure shoulder strength. This combination builds explosive pulling power and strict pressing strength. The strict press component develops pure shoulder strength. Excellent for total body strength development. More challenging than push press due to no leg assistance.');

INSERT INTO garmin_exercises (exercise_category, exercise_name, type, tags, equipment, description)
VALUES ('OLYMPIC_LIFT', 'DUMBBELL_SNATCH', 'STRENGTH', '{legs,back,shoulders,olympic lift,power,explosive,triple extension}', '{dumbbells}', 'Full dumbbell snatch from floor to overhead - explosive total body movement. Pull dumbbells from floor to overhead in one continuous motion. The dumbbell version allows for more natural movement patterns than barbell. This variation is easier on wrists and shoulders while still building explosive power. Excellent for developing unilateral power and coordination. Can be performed with one or two dumbbells. Great alternative to barbell snatch.');

INSERT INTO garmin_exercises (exercise_category, exercise_name, type, tags, equipment, description)
VALUES ('OLYMPIC_LIFT', 'MEDICINE_BALL_CLEAN', 'STRENGTH', '{legs,back,shoulders,olympic lift,power,explosive,triple extension}', '{medicine ball}', 'Explosive clean movement using a medicine ball - pull from floor to shoulders. The medicine ball provides a unique gripping challenge and allows for safe learning of clean mechanics. This variation is excellent for beginners learning Olympic movements or for conditioning work. The lighter weight allows focus on speed and technique. Can be performed at high volume for power endurance. Great teaching tool for the clean movement pattern.');

INSERT INTO garmin_exercises (exercise_category, exercise_name, type, tags, equipment, description)
VALUES ('OLYMPIC_LIFT', 'ONE_HAND_DUMBBELL_SPLIT_SNATCH', 'STRENGTH', '{legs,back,shoulders,olympic lift,power,explosive,unilateral}', '{dumbbells}', 'Single-arm dumbbell snatch performed catching in a split stance. Explosively pull one dumbbell from floor to overhead while splitting legs front and back. This advanced unilateral variation builds tremendous single-arm power and coordination. The split catch provides stability for heavier loads. Excellent for addressing imbalances and building rotational stability. Combines Olympic lifting with single-arm strength. Challenging exercise for advanced athletes.');

INSERT INTO garmin_exercises (exercise_category, exercise_name, type, tags, equipment, description)
VALUES ('OLYMPIC_LIFT', 'PUSH_JERK', 'STRENGTH', '{legs,shoulders,olympic lift,power,explosive}', '{barbell}', 'Drive barbell from shoulders to overhead using leg dip and drive, catching in a shallow dip. The push jerk uses leg drive to accelerate the bar, then dips under for the catch. This pressing variation allows for heavier weights than strict press. Essential component of Olympic weightlifting. The shallow dip catch is easier than split jerk but still allows heavy loads. Builds explosive overhead strength and power.');

INSERT INTO garmin_exercises (exercise_category, exercise_name, type, tags, equipment, description)
VALUES ('OLYMPIC_LIFT', 'SINGLE_ARM_DUMBBELL_SNATCH', 'STRENGTH', '{legs,back,shoulders,olympic lift,power,explosive,unilateral,triple extension}', '{dumbbells}', 'One of the best single-arm power exercises - explosive dumbbell snatch from floor to overhead with one arm. This unilateral movement builds tremendous single-arm power, core stability, and anti-rotation strength. The asymmetric loading challenges the entire body differently than bilateral lifts. Excellent for identifying and correcting left-right imbalances. Builds functional athletic power. Popular in CrossFit and functional training. One arm at a time.');

INSERT INTO garmin_exercises (exercise_category, exercise_name, type, tags, equipment, description)
VALUES ('OLYMPIC_LIFT', 'SINGLE_ARM_HANG_SNATCH', 'STRENGTH', '{legs,back,shoulders,olympic lift,power,explosive,unilateral}', '{dumbbells,kettlebell}', 'Single-arm snatch from hang position - explosive pull from mid-thigh to overhead with one arm. The hang position emphasizes the explosive second pull and hip extension. This unilateral variation builds single-arm power while challenging core stability and anti-rotation control. The asymmetric loading requires tremendous balance and coordination. Excellent for correcting imbalances and building functional power. Can use dumbbell or kettlebell.');

INSERT INTO garmin_exercises (exercise_category, exercise_name, type, tags, equipment, description)
VALUES ('OLYMPIC_LIFT', 'SINGLE_ARM_KETTLEBELL_SNATCH', 'STRENGTH', '{legs,back,shoulders,olympic lift,power,explosive,unilateral,triple extension}', '{kettlebell}', 'The kettlebell snatch - one of the most iconic kettlebell movements. Explosive pull from floor (or between legs) to overhead lockout with one arm. The kettlebell snatch is a conditioning and power powerhouse. This ballistic movement builds tremendous grip strength, shoulder stability, and cardiovascular endurance. Popular in kettlebell sport and military fitness. The unique kettlebell movement pattern differs from dumbbell snatch. Builds exceptional work capacity.');

INSERT INTO garmin_exercises (exercise_category, exercise_name, type, tags, equipment, description)
VALUES ('OLYMPIC_LIFT', 'SPLIT_JERK', 'STRENGTH', '{legs,shoulders,olympic lift,power,explosive}', '{barbell}', 'Generic split jerk movement - drive weight from shoulders to overhead while splitting legs. This fundamental Olympic weightlifting movement allows for maximum overhead loads. The split stance provides exceptional stability under heavy weight. Essential for clean and jerk performance. The most common jerk variation in competitive weightlifting. Requires speed, timing, and coordination. Builds explosive pressing power and leg drive.');

INSERT INTO garmin_exercises (exercise_category, exercise_name, type, tags, equipment, description)
VALUES ('OLYMPIC_LIFT', 'SQUAT_CLEAN_AND_JERK', 'STRENGTH', '{legs,back,shoulders,squat pattern,olympic lift,power,explosive,triple extension}', '{barbell}', 'The complete Olympic clean and jerk with full squat catch - the ultimate test of total body strength and power. Explosive pull from floor, catch in deep front squat, stand up, then jerk overhead. This is one of two Olympic competition lifts. Combines maximum pulling power, deep squatting strength, and explosive overhead pressing. The most complete strength and power exercise. Builds exceptional total body athleticism, strength, and coordination.');