-- Garmin Exercises: PLANK

-- Total exercises: 131

-- Generated: 2025-11-18T02:24:16.087Z


INSERT INTO garmin_exercises (exercise_category, exercise_name, type, tags, equipment, description)
VALUES ('PLANK', '_45_DEGREE_PLANK', 'STRENGTH', '{core,abs,shoulders,isometric}', '{bodyweight}', 'Plank performed with body at 45-degree angle - hands elevated on bench or box. This incline variation makes planks more accessible for beginners. The angle reduces the percentage of bodyweight supported, building foundational core strength. Excellent progression toward full planks. The elevated position maintains proper form while building strength. Great for learning proper plank alignment and core engagement.');

INSERT INTO garmin_exercises (exercise_category, exercise_name, type, tags, equipment, description)
VALUES ('PLANK', '_90_DEGREE_STATIC_HOLD', 'STRENGTH', '{core,abs,hip flexors,shoulders,isometric}', '{bodyweight}', 'Advanced static hold with body at 90-degree angle - typically L-sit or hanging L-hold position. Hold body with legs extended at 90 degrees from torso. This brutally challenging isometric exercise builds exceptional core strength, hip flexor endurance, and shoulder stability. The 90-degree position requires tremendous abdominal and hip flexor strength. Elite-level core exercise. Common in gymnastics and advanced calisthenics.');

INSERT INTO garmin_exercises (exercise_category, exercise_name, type, tags, equipment, description)
VALUES ('PLANK', 'BEAR_CRAWL', 'STRENGTH', '{core,abs,shoulders,conditioning,full body}', '{bodyweight}', 'Crawl on hands and feet with knees hovering off ground - THE foundational crawling pattern. Move forward, backward, or laterally while maintaining stable core. This full-body movement builds core stability, shoulder strength, coordination, and cardiovascular endurance. Excellent warm-up exercise and conditioning tool. Used extensively in functional training, sports conditioning, and movement training. Simple but brutally effective.');

INSERT INTO garmin_exercises (exercise_category, exercise_name, type, tags, equipment, description)
VALUES ('PLANK', 'CROSS_BODY_MOUNTAIN_CLIMBER', 'STRENGTH', '{core,abs,obliques,conditioning,cardio}', '{bodyweight}', 'Mountain climber variation bringing knee toward opposite elbow - targeting obliques and rotation. In plank position, drive knee across body toward opposite elbow. This dynamic oblique exercise builds rotational core strength and cardiovascular endurance. The cross-body pattern engages obliques more than standard mountain climbers. Excellent for core conditioning and fat loss. Popular in HIIT workouts and circuit training.');

INSERT INTO garmin_exercises (exercise_category, exercise_name, type, tags, equipment, description)
VALUES ('PLANK', 'ELBOW_PLANK_PIKE_JACKS', 'STRENGTH', '{core,abs,shoulders,hip flexors,conditioning}', '{bodyweight}', 'Dynamic plank variation combining pike position with jumping jacks motion. From elbow plank, jump feet apart while piking hips up, then jump back together. This challenging exercise combines core strength, shoulder stability, hip flexor engagement, and cardiovascular conditioning. The jumping motion adds plyometric element. Excellent for advanced core training and athletic conditioning. Builds explosive core power.');

INSERT INTO garmin_exercises (exercise_category, exercise_name, type, tags, equipment, description)
VALUES ('PLANK', 'ELEVATED_FEET_PLANK', 'STRENGTH', '{core,abs,shoulders,isometric}', '{bench,box}', 'Plank with feet elevated on bench or box - significantly harder than standard plank. The elevation increases the percentage of bodyweight supported and shifts more load to shoulders and upper core. This progression builds exceptional core and shoulder strength. The declined angle increases difficulty dramatically. Excellent for advanced plankers. Small elevation changes make big difficulty differences.');

INSERT INTO garmin_exercises (exercise_category, exercise_name, type, tags, equipment, description)
VALUES ('PLANK', 'ELEVATOR_ABS', 'STRENGTH', '{core,abs,isometric}', '{bodyweight}', 'Plank variation with pulsing hip movement - lower hips slightly then elevate back to plank. The small pulsing movements maintain constant tension on the core. This dynamic plank challenges endurance and control. The micro-movements ("elevator" up and down) build exceptional core stability. Excellent for building time under tension and muscular endurance. Harder than static plank despite small range of motion.');

INSERT INTO garmin_exercises (exercise_category, exercise_name, type, tags, equipment, description)
VALUES ('PLANK', 'EXTENDED_PLANK', 'STRENGTH', '{core,abs,shoulders,isometric}', '{bodyweight}', 'Advanced plank with hands positioned further forward - extending the lever arm. Walk hands forward 6-12 inches beyond shoulders while maintaining rigid plank position. This brutal progression dramatically increases core and shoulder demands through increased leverage. The extended position requires exceptional anti-extension strength. One of the hardest plank variations. Small hand movements create massive difficulty increases.');

INSERT INTO garmin_exercises (exercise_category, exercise_name, type, tags, equipment, description)
VALUES ('PLANK', 'FULL_PLANK_PASSE_TWIST', 'STRENGTH', '{core,abs,obliques,hip flexors,balance}', '{bodyweight}', 'Dynamic plank combining leg lift with rotational twist. From plank, lift knee toward chest (passe position) while rotating torso. This complex movement pattern challenges core stability, hip flexor strength, and rotational control simultaneously. The passe twist combination builds multi-planar core strength. Excellent for athletic training and functional core development. Requires significant balance and coordination.');

INSERT INTO garmin_exercises (exercise_category, exercise_name, type, tags, equipment, description)
VALUES ('PLANK', 'INCHING_ELBOW_PLANK', 'STRENGTH', '{core,abs,shoulders}', '{bodyweight}', 'Dynamic plank where you "inch" forward and backward on elbows. From elbow plank, use forearms to inch body forward, then inch backward. This challenging variation adds dynamic movement while maintaining plank position. The inching motion builds exceptional shoulder stability and core control. The movement requires constant core engagement to prevent sagging. Excellent for building dynamic core strength and shoulder endurance.');

INSERT INTO garmin_exercises (exercise_category, exercise_name, type, tags, equipment, description)
VALUES ('PLANK', 'INCHWORM_TO_SIDE_PLANK', 'STRENGTH', '{core,abs,obliques,shoulders,hamstrings,full body}', '{bodyweight}', 'Complex movement combining inchworm walkout with side plank rotation. Walk hands forward (inchworm), rotate into side plank, return and repeat. This full-body exercise builds core strength, shoulder stability, hamstring flexibility, and coordination. The combination challenges multiple movement patterns. Excellent warm-up and conditioning exercise. Builds dynamic core control and mobility simultaneously.');

INSERT INTO garmin_exercises (exercise_category, exercise_name, type, tags, equipment, description)
VALUES ('PLANK', 'KNEELING_PLANK', 'STRENGTH', '{core,abs,shoulders,isometric}', '{bodyweight}', 'Modified plank from knees instead of toes - THE beginner plank progression. Support body weight on forearms and knees instead of feet. This accessible variation reduces the load, making planks achievable for beginners. The shortened lever arm decreases difficulty while teaching proper form. Essential progression for building foundational core strength. Perfect starting point before progressing to full planks.');

INSERT INTO garmin_exercises (exercise_category, exercise_name, type, tags, equipment, description)
VALUES ('PLANK', 'KNEELING_SIDE_PLANK_WITH_LEG_LIFT', 'STRENGTH', '{core,abs,obliques,hip abductors,balance}', '{bodyweight}', 'Modified side plank from knees with top leg lift. From kneeling side plank position, lift top leg toward ceiling. This progression adds hip abductor work to core stability demands. The leg lift increases difficulty while maintaining the accessible kneeling base. Excellent for building lateral core strength and hip stability. Good bridge between basic kneeling side plank and full side plank.');

INSERT INTO garmin_exercises (exercise_category, exercise_name, type, tags, equipment, description)
VALUES ('PLANK', 'LATERAL_ROLL', 'STRENGTH', '{back,core,abs,obliques}', '{bodyweight}', 'Dynamic plank variation rolling from front plank to side plank and back. Roll from standard plank to side plank on one side, back to center, then to other side. This flowing movement builds multi-planar core strength and coordination. The rolling motion engages obliques and teaches smooth transitions. Excellent for dynamic core control and movement quality. Builds rotational stability.');

INSERT INTO garmin_exercises (exercise_category, exercise_name, type, tags, equipment, description)
VALUES ('PLANK', 'LYING_REVERSE_PLANK', 'STRENGTH', '{glutes,hamstrings,lower back,shoulders,isometric}', '{bodyweight}', 'Reverse plank position - face up, supported on hands and heels with body straight. This posterior chain exercise targets glutes, hamstrings, and lower back while building shoulder stability. The reverse position creates opposite demands from front planks. Excellent for balanced core development and posterior chain strength. Often neglected but essential for complete core training. Builds anti-flexion strength.');

INSERT INTO garmin_exercises (exercise_category, exercise_name, type, tags, equipment, description)
VALUES ('PLANK', 'MEDICINE_BALL_MOUNTAIN_CLIMBER', 'STRENGTH', '{core,abs,shoulders,conditioning,cardio}', '{medicine ball}', 'Mountain climbers performed with hands on a medicine ball. The unstable ball surface dramatically increases core stability and shoulder demands. Drive knees toward chest alternately while balancing on the ball. This challenging variation builds exceptional core strength, shoulder stability, and cardiovascular endurance. The instability requires constant micro-adjustments. Advanced progression for mountain climbers.');

INSERT INTO garmin_exercises (exercise_category, exercise_name, type, tags, equipment, description)
VALUES ('PLANK', 'MODIFIED_MOUNTAIN_CLIMBER_AND_EXTENSION', 'STRENGTH', '{core,abs,hip flexors,glutes,conditioning}', '{bodyweight}', 'Mountain climber variation combining knee drive with hip extension. Drive knee toward chest, then extend same leg straight back. This dynamic movement pattern combines hip flexor engagement with glute activation. The extension phase adds posterior chain work to standard mountain climbers. Excellent for building complete hip and core control. Combines conditioning with strength work.');

INSERT INTO garmin_exercises (exercise_category, exercise_name, type, tags, equipment, description)
VALUES ('PLANK', 'MOUNTAIN_CLIMBER', 'STRENGTH', '{core,abs,hip flexors,shoulders,conditioning,cardio}', '{bodyweight}', 'THE classic mountain climber - from plank position, rapidly alternate driving knees toward chest. This dynamic core exercise builds abdominal strength, hip flexor endurance, shoulder stability, and cardiovascular conditioning simultaneously. The rapid movement elevates heart rate quickly. Essential exercise for core conditioning and fat loss. Used extensively in HIIT workouts and circuit training. Simple but brutally effective.');

INSERT INTO garmin_exercises (exercise_category, exercise_name, type, tags, equipment, description)
VALUES ('PLANK', 'MOUNTAIN_CLIMBER_ON_SLIDING_DISCS', 'STRENGTH', '{core,abs,hip flexors,shoulders}', '{sliding discs}', 'Mountain climbers performed with feet on sliding discs. The sliders create a smooth, controlled gliding motion versus the jumping version. This variation increases time under tension and requires constant core control. The sliding motion reduces impact while maintaining intensity. Excellent for building controlled core strength and hip flexor endurance. The continuous sliding demands exceptional stability.');

INSERT INTO garmin_exercises (exercise_category, exercise_name, type, tags, equipment, description)
VALUES ('PLANK', 'MOUNTAIN_CLIMBER_WITH_FEET_ON_BOSU_BALL', 'STRENGTH', '{core,abs,hip flexors,shoulders,balance,conditioning}', '{bosu ball}', 'Mountain climbers with feet on unstable BOSU ball surface. The instability dramatically increases core stability demands and balance requirements. Drive knees toward chest while maintaining balance on the BOSU. This advanced variation builds exceptional core control and proprioception. The unstable surface requires constant micro-adjustments. Elite-level core conditioning exercise.');

INSERT INTO garmin_exercises (exercise_category, exercise_name, type, tags, equipment, description)
VALUES ('PLANK', 'MOUNTAIN_CLIMBER_WITH_HANDS_ON_BENCH', 'STRENGTH', '{core,abs,hip flexors,shoulders,conditioning}', '{bench}', 'Incline mountain climbers with hands elevated on bench. The elevated hand position reduces the intensity, making mountain climbers more accessible. This regression allows focus on form and building endurance. Excellent progression for beginners working toward full mountain climbers. The incline angle decreases the percentage of bodyweight supported. Great conditioning tool for all levels.');

INSERT INTO garmin_exercises (exercise_category, exercise_name, type, tags, equipment, description)
VALUES ('PLANK', 'MOUNTAIN_CLIMBER_WITH_HANDS_ON_SWISS_BALL', 'STRENGTH', '{core,abs,hip flexors,shoulders,balance,conditioning}', '{swiss ball}', 'Mountain climbers with hands on unstable swiss ball. The ball creates extreme instability, dramatically increasing core and shoulder stability demands. Drive knees toward chest while maintaining balance on the ball. This brutally difficult variation builds exceptional core control and shoulder stability. The unstable surface requires tremendous focus and control. Elite-level exercise for advanced athletes.');

INSERT INTO garmin_exercises (exercise_category, exercise_name, type, tags, equipment, description)
VALUES ('PLANK', 'PLANK', 'STRENGTH', '{core,abs,shoulders,isometric}', '{bodyweight}', 'THE fundamental plank - the king of core exercises. Hold rigid body position supported on forearms and toes. This isometric exercise builds exceptional core strength, shoulder stability, and full-body tension. The plank is the foundation of core training. Essential for spine health, athletic performance, and functional strength. Teaches proper core bracing for all movements. One of the most important exercises in fitness.');

INSERT INTO garmin_exercises (exercise_category, exercise_name, type, tags, equipment, description)
VALUES ('PLANK', 'PLANK_JACKS_WITH_FEET_ON_SLIDING_DISCS', 'STRENGTH', '{core,abs,hip abductors,hip adductors,shoulders,conditioning}', '{sliding discs}', 'Plank jacks performed with feet on sliding discs. From plank, slide feet apart (jack out) and back together. The sliders create smooth, controlled movement with constant tension. This dynamic variation builds core stability, hip strength, and shoulder endurance. The sliding motion reduces impact while maintaining high intensity. Excellent for building controlled core strength and hip stability.');

INSERT INTO garmin_exercises (exercise_category, exercise_name, type, tags, equipment, description)
VALUES ('PLANK', 'PLANK_KNEE_TWIST', 'STRENGTH', '{core,abs,obliques,hip flexors}', '{bodyweight}', 'Dynamic plank bringing knee toward opposite elbow with twist. From plank, drive knee across body with rotating motion. This oblique-focused variation builds rotational core strength and hip mobility. The twisting motion engages obliques intensely. Excellent for building functional rotational power. Combines core stability with dynamic movement.');

INSERT INTO garmin_exercises (exercise_category, exercise_name, type, tags, equipment, description)
VALUES ('PLANK', 'PLANK_PIKE_JUMPS', 'STRENGTH', '{core,abs,hip flexors,shoulders,plyometric,conditioning}', '{bodyweight}', 'Explosive plank variation - jump feet toward hands into pike position, then jump back. From plank, explosively jump feet forward (piking hips up), then jump back to plank. This plyometric core exercise builds explosive power, hip flexor strength, and cardiovascular conditioning. The jumping motion adds significant intensity. Excellent for athletic training and high-intensity conditioning. Builds explosive core power.');

INSERT INTO garmin_exercises (exercise_category, exercise_name, type, tags, equipment, description)
VALUES ('PLANK', 'PLANK_PIKES', 'STRENGTH', '{core,abs,hip flexors,shoulders,hamstrings}', '{bodyweight}', 'Dynamic plank movement piking hips up toward ceiling. From plank, press hips up into an inverted V position (pike), then return. This controlled movement builds core strength, shoulder stability, and hamstring flexibility. The pike position engages the entire core through flexion. Excellent for building dynamic core control and mobility. The non-jumping version of plank pike jumps.');

INSERT INTO garmin_exercises (exercise_category, exercise_name, type, tags, equipment, description)
VALUES ('PLANK', 'PLANK_TO_STAND_UP', 'STRENGTH', '{core,abs,legs,full body,functional}', '{bodyweight}', 'Complex full-body movement from plank to standing position. From plank, transition through positions to stand up, then return to plank. This functional exercise builds core strength, mobility, coordination, and total body control. The complex movement pattern challenges multiple planes and positions. Excellent for building practical strength and movement quality. Great warm-up and conditioning exercise.');

INSERT INTO garmin_exercises (exercise_category, exercise_name, type, tags, equipment, description)
VALUES ('PLANK', 'PLANK_WITH_ARM_RAISE', 'STRENGTH', '{core,abs,shoulders,balance,anti-rotation,isometric}', '{bodyweight}', 'Plank with one arm extended forward - challenges anti-rotation control. From plank, lift and extend one arm straight ahead while maintaining position. This unilateral variation dramatically increases core stability demands and anti-rotation strength. The single-arm support challenges balance and shoulder stability. Excellent for building asymmetrical strength and identifying imbalances. Progress from holding briefly to longer durations.');

INSERT INTO garmin_exercises (exercise_category, exercise_name, type, tags, equipment, description)
VALUES ('PLANK', 'PLANK_WITH_FEET_ON_SWISS_BALL', 'STRENGTH', '{core,abs,shoulders,balance,isometric}', '{swiss ball}', 'Advanced plank with feet on unstable swiss ball. The ball creates significant instability, dramatically increasing core and shoulder demands. This challenging variation requires constant micro-adjustments to maintain balance. Builds exceptional core stability and proprioception. The unstable surface forces deep core engagement. Elite progression for standard planks. Small ball movements create massive stability challenges.');

INSERT INTO garmin_exercises (exercise_category, exercise_name, type, tags, equipment, description)
VALUES ('PLANK', 'PLANK_WITH_KNEE_TO_ELBOW', 'STRENGTH', '{core,abs,obliques,hip flexors}', '{bodyweight}', 'Dynamic plank bringing knee to same-side elbow. From plank, draw knee toward elbow on the same side, then extend back. This movement builds core strength, hip flexor endurance, and oblique engagement. The knee-to-elbow pattern challenges lateral flexion control. Excellent for building dynamic core stability and hip mobility. Less rotational than cross-body variations.');

INSERT INTO garmin_exercises (exercise_category, exercise_name, type, tags, equipment, description)
VALUES ('PLANK', 'PLANK_WITH_LEG_LIFT', 'STRENGTH', '{core,abs,glutes,balance,anti-rotation,isometric}', '{bodyweight}', 'Plank with one leg lifted - challenges anti-rotation and glute strength. From plank, lift one leg off ground while maintaining neutral spine and level hips. This unilateral variation increases core stability demands and engages the glutes. The single-leg support requires tremendous anti-rotation control. Excellent for building asymmetrical stability and posterior chain strength. Alternate legs or hold one side.');

INSERT INTO garmin_exercises (exercise_category, exercise_name, type, tags, equipment, description)
VALUES ('PLANK', 'PLANK_WITH_OBLIQUE_CRUNCH', 'STRENGTH', '{core,abs,obliques,hip flexors}', '{bodyweight}', 'Side plank variation bringing knee to chest with oblique crunch. From side plank or rotating plank position, crunch knee toward chest engaging obliques. This dynamic movement builds lateral core strength and oblique development. The crunching motion intensely targets the obliques. Excellent for building rotational core strength and defining the obliques. Combines isometric hold with dynamic crunch.');

INSERT INTO garmin_exercises (exercise_category, exercise_name, type, tags, equipment, description)
VALUES ('PLANK', 'PLYOMETRIC_SIDE_PLANK', 'STRENGTH', '{core,abs,obliques,shoulders,plyometric,power}', '{bodyweight}', 'Explosive side plank variation - jump explosively from one side plank to the other. Rapidly switch from left side plank to right side plank with explosive rotation. This advanced plyometric exercise builds explosive rotational power and lateral core strength. The jumping motion adds significant intensity and power development. Elite-level core exercise for athletes. Builds explosive oblique strength.');

INSERT INTO garmin_exercises (exercise_category, exercise_name, type, tags, equipment, description)
VALUES ('PLANK', 'RING_PLANK_SPRAWLS', 'STRENGTH', '{core,abs,shoulders,legs,conditioning}', '{rings}', 'Plank sprawls performed holding gymnastics rings. From ring plank, jump feet back and forth in sprawl motion. The unstable rings create extreme stability demands for shoulders and core. This brutal exercise builds exceptional upper body stability and full-body conditioning. The ring instability makes every rep dramatically harder. Elite exercise for gymnasts and advanced athletes. Builds extraordinary core and shoulder control.');

INSERT INTO garmin_exercises (exercise_category, exercise_name, type, tags, equipment, description)
VALUES ('PLANK', 'ROLLING_SIDE_PLANK', 'STRENGTH', '{core,abs,obliques,shoulders}', '{bodyweight}', 'Dynamic plank transitioning smoothly from side plank to side plank. Roll from left side plank through front plank to right side plank continuously. This flowing movement builds multi-planar core strength and shoulder mobility. The rolling motion challenges transitional stability and control. Excellent for building dynamic core strength and movement quality. Combines multiple plank variations into one fluid exercise.');

INSERT INTO garmin_exercises (exercise_category, exercise_name, type, tags, equipment, description)
VALUES ('PLANK', 'SIDE_KICK_PLANK', 'STRENGTH', '{core,abs,obliques,hip abductors,balance}', '{bodyweight}', 'Side plank with top leg kicking forward and back. From side plank, perform controlled kicks with top leg. This dynamic variation combines lateral core stability with hip abductor work and balance. The kicking motion challenges core control while in unstable side position. Excellent for building lateral core strength and hip mobility. Combines isometric hold with dynamic movement.');

INSERT INTO garmin_exercises (exercise_category, exercise_name, type, tags, equipment, description)
VALUES ('PLANK', 'SIDE_PLANK', 'STRENGTH', '{core,abs,obliques,shoulders,isometric}', '{bodyweight}', 'THE fundamental side plank - essential for lateral core strength. Support body on one forearm and side of foot, maintaining straight line. This isometric exercise builds exceptional oblique strength, lateral stability, and shoulder endurance. Essential for balanced core development and spine health. The side plank targets muscles missed by front planks. Critical for preventing lateral spinal collapse. One of the most important core exercises.');

INSERT INTO garmin_exercises (exercise_category, exercise_name, type, tags, equipment, description)
VALUES ('PLANK', 'SIDE_PLANK_AND_ROW', 'STRENGTH', '{core,abs,obliques,back,shoulders,anti-rotation}', '{dumbbells}', 'Side plank with dumbbell row - combining lateral core stability with pulling strength. From side plank on one hand, row a dumbbell with free hand. This complex exercise builds oblique strength, anti-rotation control, and upper back strength simultaneously. The rowing motion creates tremendous rotational challenge. Elite combination exercise for functional strength. Builds exceptional total body control.');

INSERT INTO garmin_exercises (exercise_category, exercise_name, type, tags, equipment, description)
VALUES ('PLANK', 'SIDE_PLANK_LIFT', 'STRENGTH', '{core,abs,obliques,hips}', '{bodyweight}', 'Dynamic side plank with hip dip and lift. From side plank, lower hips toward ground then lift back up (or higher). This dynamic variation adds movement to side plank, increasing time under tension and oblique engagement. The dipping and lifting motion builds exceptional lateral core endurance. Harder than static side plank despite looking simple. Builds oblique strength and endurance.');

INSERT INTO garmin_exercises (exercise_category, exercise_name, type, tags, equipment, description)
VALUES ('PLANK', 'SIDE_PLANK_TO_PLANK_WITH_REACH_UNDER', 'STRENGTH', '{core,abs,obliques,shoulders,rotation}', '{bodyweight}', 'Complex rotational plank movement - from side plank, rotate to front plank while reaching arm under body. Thread top arm under torso with rotation, then return. This advanced dynamic exercise builds rotational core strength, shoulder mobility, and coordination. The reaching motion creates intense oblique engagement. Excellent for building functional rotational control. Combines multiple movement patterns.');

INSERT INTO garmin_exercises (exercise_category, exercise_name, type, tags, equipment, description)
VALUES ('PLANK', 'SIDE_PLANK_WITH_ELBOW_ON_BOSU_BALL', 'STRENGTH', '{core,abs,obliques,shoulders,balance,isometric}', '{bosu ball}', 'Side plank with bottom elbow on unstable BOSU ball. The ball surface creates extreme lateral instability, dramatically increasing oblique and shoulder demands. This advanced variation requires constant micro-adjustments to prevent rolling. Builds exceptional lateral core stability and proprioception. The instability makes this brutally difficult. Elite progression for side planks.');

INSERT INTO garmin_exercises (exercise_category, exercise_name, type, tags, equipment, description)
VALUES ('PLANK', 'SIDE_PLANK_WITH_FEET_ON_BENCH', 'STRENGTH', '{core,abs,obliques,shoulders,isometric}', '{bench}', 'Elevated side plank with feet on bench - significantly harder than floor version. The elevation increases leverage and percentage of bodyweight supported. This advanced progression builds exceptional oblique and shoulder strength. The increased difficulty comes from greater lever arm length. Excellent for athletes who have mastered standard side planks. Small elevation creates large difficulty increase.');

INSERT INTO garmin_exercises (exercise_category, exercise_name, type, tags, equipment, description)
VALUES ('PLANK', 'SIDE_PLANK_WITH_KNEE_CIRCLE', 'STRENGTH', '{core,abs,obliques,hip flexors,hip mobility}', '{bodyweight}', 'Side plank with top knee performing circles. From side plank, draw circles in the air with top knee. This dynamic movement combines lateral core stability with hip mobility work. The circling motion challenges balance and control while opening hips. Excellent for building core stability and hip flexibility simultaneously. The movement pattern improves hip mobility.');

INSERT INTO garmin_exercises (exercise_category, exercise_name, type, tags, equipment, description)
VALUES ('PLANK', 'SIDE_PLANK_WITH_KNEE_TUCK', 'STRENGTH', '{core,abs,obliques,hip flexors}', '{bodyweight}', 'Side plank with top knee tuck - bring knee toward chest. From side plank, tuck top knee toward chest, then extend. This dynamic movement adds hip flexor work to lateral core stability. The tucking motion challenges balance and oblique control. Excellent for building functional lateral core strength. Combines isometric hold with dynamic leg movement.');

INSERT INTO garmin_exercises (exercise_category, exercise_name, type, tags, equipment, description)
VALUES ('PLANK', 'SIDE_PLANK_WITH_LEG_LIFT', 'STRENGTH', '{core,abs,obliques,hip abductors,balance,isometric}', '{bodyweight}', 'Classic side plank with top leg lift - THE advanced side plank progression. From side plank, lift top leg toward ceiling. This advanced variation dramatically increases oblique demands and adds hip abductor work. The leg lift challenges balance and requires exceptional lateral core control. One of the best oblique exercises. Excellent for building hip and core strength simultaneously.');

INSERT INTO garmin_exercises (exercise_category, exercise_name, type, tags, equipment, description)
VALUES ('PLANK', 'SIDE_PLANK_WITH_REACH_UNDER', 'STRENGTH', '{core,abs,obliques,shoulders,rotation}', '{bodyweight}', 'Side plank with top arm reaching under body. From side plank, thread top arm under torso with rotation, then return. This rotational movement builds oblique strength, thoracic mobility, and shoulder flexibility. The reaching motion creates intense oblique engagement and anti-rotation control. Excellent for building functional core strength and upper body mobility. Dynamic side plank variation.');

INSERT INTO garmin_exercises (exercise_category, exercise_name, type, tags, equipment, description)
VALUES ('PLANK', 'SINGLE_LEG_ELEVATED_FEET_PLANK', 'STRENGTH', '{core,abs,glutes,anti-rotation,unilateral,isometric}', '{bench,box}', 'Elevated feet plank with only one foot on the bench - combining elevation and unilateral challenge. One foot elevated, other leg lifted off ground. This brutally difficult variation combines the demands of elevated plank with single-leg instability. Requires exceptional anti-rotation control and glute engagement. Elite-level plank progression. Addresses imbalances while building maximum core strength.');

INSERT INTO garmin_exercises (exercise_category, exercise_name, type, tags, equipment, description)
VALUES ('PLANK', 'SINGLE_LEG_FLEX_AND_EXTEND', 'STRENGTH', '{core,abs,hip flexors,glutes,anti-rotation,unilateral}', '{bodyweight}', 'Dynamic single-leg plank variation - flex knee to chest, then extend leg straight back. From plank position on one leg, tuck knee to chest, then extend leg behind you. This unilateral movement builds core stability, hip flexor strength, and glute engagement. The asymmetric loading requires tremendous anti-rotation control. Excellent for addressing imbalances and building single-leg control.');

INSERT INTO garmin_exercises (exercise_category, exercise_name, type, tags, equipment, description)
VALUES ('PLANK', 'SINGLE_LEG_SIDE_PLANK', 'STRENGTH', '{core,abs,obliques,hip abductors,balance,unilateral,isometric}', '{bodyweight}', 'Side plank supported on one foot only - THE most difficult side plank variation. Balance on one forearm and one foot with other leg lifted. This elite-level exercise requires exceptional oblique strength, hip stability, and balance. The single-leg base creates maximum instability. Only for advanced athletes who have mastered standard side planks. Builds extraordinary lateral core control.');

INSERT INTO garmin_exercises (exercise_category, exercise_name, type, tags, equipment, description)
VALUES ('PLANK', 'SPIDERMAN_PLANK', 'STRENGTH', '{core,abs,obliques,hip flexors,hip mobility}', '{bodyweight}', 'Plank with knee driving toward same-side elbow outside the body - like climbing. From plank, bring knee up and out toward elbow. This dynamic movement builds core stability, hip flexor strength, and hip mobility. The wide knee path mimics climbing motion (hence "spiderman"). Excellent for building functional hip mobility and core control. Popular in functional training and martial arts.');

INSERT INTO garmin_exercises (exercise_category, exercise_name, type, tags, equipment, description)
VALUES ('PLANK', 'STRAIGHT_ARM_PLANK', 'STRENGTH', '{core,abs,shoulders,isometric}', '{bodyweight}', 'High plank position - plank on hands instead of forearms. Maintain rigid body line supported on straight arms and toes. This variation emphasizes shoulder stability more than elbow plank. The straight-arm position is slightly easier on core but harder on shoulders. Essential for push-up progression and overhead pressing strength. Foundation for many dynamic plank variations.');

INSERT INTO garmin_exercises (exercise_category, exercise_name, type, tags, equipment, description)
VALUES ('PLANK', 'STRAIGHT_ARM_PLANK_WITH_SHOULDER_TOUCH', 'STRENGTH', '{shoulders,core,abs,anti-rotation}', '{bodyweight}', 'High plank with alternating shoulder taps - touch opposite shoulder with each hand. From straight-arm plank, tap left shoulder with right hand, then right shoulder with left hand. This anti-rotation exercise builds exceptional core stability and shoulder control. The weight shift creates rotational challenge. Excellent for building anti-rotation strength and shoulder stability. Keep hips square throughout.');

INSERT INTO garmin_exercises (exercise_category, exercise_name, type, tags, equipment, description)
VALUES ('PLANK', 'SWISS_BALL_PLANK', 'STRENGTH', '{core,abs,shoulders,balance,isometric}', '{swiss ball}', 'Plank with forearms on unstable swiss ball. The ball creates significant instability, dramatically increasing core and shoulder demands. This advanced variation requires constant micro-adjustments to maintain balance. Builds exceptional core stability and shoulder control. The unstable surface forces deep core activation. Advanced progression for standard planks. Small ball movements create big stability challenges.');

INSERT INTO garmin_exercises (exercise_category, exercise_name, type, tags, equipment, description)
VALUES ('PLANK', 'SWISS_BALL_PLANK_LEG_LIFT', 'STRENGTH', '{core,abs,glutes,shoulders,balance,anti-rotation}', '{swiss ball}', 'Swiss ball plank with single-leg lift - combining instability and unilateral challenge. Forearms on ball, lift one leg off ground. This elite-level variation combines ball instability with single-leg demands. Requires exceptional core stability, glute engagement, and anti-rotation control. The asymmetric loading on unstable surface creates maximum challenge. Only for very advanced athletes.');

INSERT INTO garmin_exercises (exercise_category, exercise_name, type, tags, equipment, description)
VALUES ('PLANK', 'SWISS_BALL_PLANK_LEG_LIFT_AND_HOLD', 'STRENGTH', '{core,abs,glutes,shoulders,balance,anti-rotation,isometric}', '{swiss ball}', 'Swiss ball plank with sustained single-leg hold - holding the leg lift position. Forearms on ball, lift and hold one leg elevated. This brutal isometric variation combines ball instability with prolonged asymmetric loading. The extended hold time builds exceptional endurance and control. The sustained unilateral position requires tremendous anti-rotation strength. Elite-level core endurance exercise.');

INSERT INTO garmin_exercises (exercise_category, exercise_name, type, tags, equipment, description)
VALUES ('PLANK', 'SWISS_BALL_PLANK_WITH_FEET_ON_BENCH', 'STRENGTH', '{core,abs,shoulders,balance,isometric}', '{swiss ball,bench}', 'The ultimate plank challenge - forearms on swiss ball with feet elevated on bench. This extreme variation combines ball instability with elevated feet positioning. Creates maximum core and shoulder demands through dual instability/elevation. Only for elite-level athletes. The combination of unstable base and elevated feet is brutally difficult. Builds extraordinary core and shoulder control.');

INSERT INTO garmin_exercises (exercise_category, exercise_name, type, tags, equipment, description)
VALUES ('PLANK', 'SWISS_BALL_PRONE_JACKKNIFE', 'STRENGTH', '{core,abs,hip flexors,shoulders}', '{swiss ball}', 'Dynamic plank exercise - from plank with feet on ball, pike hips up pulling ball toward chest. Hands on floor, shins on ball. Pull ball forward by piking hips up, then extend back. This advanced core exercise builds exceptional abdominal strength and hip flexor power. The ball rolling adds instability throughout. One of the best swiss ball core exercises. Builds dynamic core strength and control.');

INSERT INTO garmin_exercises (exercise_category, exercise_name, type, tags, equipment, description)
VALUES ('PLANK', 'SWISS_BALL_SIDE_PLANK', 'STRENGTH', '{core,abs,obliques,shoulders,balance,isometric}', '{swiss ball}', 'Side plank with forearm on unstable swiss ball. The ball creates extreme lateral instability, dramatically increasing oblique and shoulder demands. This advanced variation requires constant balance adjustments. Builds exceptional lateral core stability and proprioception. The unstable surface forces deep oblique activation. Elite side plank progression. One of the hardest side plank variations.');

INSERT INTO garmin_exercises (exercise_category, exercise_name, type, tags, equipment, description)
VALUES ('PLANK', 'T_STABILIZATION', 'STRENGTH', '{core,abs,obliques,shoulders,rotation}', '{bodyweight}', 'Plank-to-side-plank rotation with arm reach - body forms a "T" shape. From straight-arm plank, rotate to side plank reaching arm toward ceiling. This dynamic rotational exercise builds core stability, shoulder mobility, and coordination. The T position requires balance and oblique control. Excellent for building functional rotational strength and shoulder stability. Combines plank variations with rotation.');

INSERT INTO garmin_exercises (exercise_category, exercise_name, type, tags, equipment, description)
VALUES ('PLANK', 'THREE_WAY_PLANK', 'STRENGTH', '{core,abs,obliques,shoulders,isometric}', '{bodyweight}', 'Plank sequence holding three positions - front plank, right side plank, left side plank. Hold each position for designated time, rotating through all three. This comprehensive core workout targets abs, obliques, and shoulders from multiple angles. The tri-planar approach builds complete core strength. Excellent for building total core endurance and stability. Combines the benefits of all plank variations.');

INSERT INTO garmin_exercises (exercise_category, exercise_name, type, tags, equipment, description)
VALUES ('PLANK', 'TOWEL_PLANK_AND_KNEE_IN', 'STRENGTH', '{core,abs,hip flexors,shoulders}', '{towels}', 'Plank with feet on towels, sliding knees toward chest. On smooth floor, place feet on towels. From plank, slide both knees toward chest, then extend back. This dynamic core exercise combines the benefits of mountain climbers with controlled sliding motion. The towels create smooth, continuous tension. Excellent for building core strength and hip flexor endurance. Lower-impact alternative to jumping mountain climbers.');

INSERT INTO garmin_exercises (exercise_category, exercise_name, type, tags, equipment, description)
VALUES ('PLANK', 'TURKISH_GET_UP_TO_SIDE_PLANK', 'STRENGTH', '{core,abs,obliques,shoulders,full body,functional}', '{kettlebell,dumbbells}', 'Partial Turkish get-up stopping at side plank position. From lying with weight overhead, rise to side plank position. This functional movement combines the Turkish get-up with side plank hold. Builds total body strength, shoulder stability, and core control. The complex movement pattern challenges coordination and multi-planar strength. Excellent for building functional strength and movement quality.');

INSERT INTO garmin_exercises (exercise_category, exercise_name, type, tags, equipment, description)
VALUES ('PLANK', 'TWO_POINT_PLANK', 'STRENGTH', '{core,abs,glutes,shoulders,balance,anti-rotation,isometric}', '{bodyweight}', 'Advanced plank supported on only two points - opposite arm and leg. Lift one arm and opposite leg simultaneously while maintaining plank position. This challenging variation creates maximum anti-rotation demands and balance requirements. The two-point base requires exceptional core control and glute engagement. Elite-level plank progression for advanced athletes. Builds extraordinary stability and coordination.');

INSERT INTO garmin_exercises (exercise_category, exercise_name, type, tags, equipment, description)
VALUES ('PLANK', 'WEIGHTED_45_DEGREE_PLANK', 'STRENGTH', '{core,abs,shoulders,isometric}', '{weight plates,weight vest}', 'Incline plank with weight added - typically weight plate on upper back. Hands elevated on bench or box at 45-degree angle with added resistance. The weight increases core and shoulder demands while maintaining the accessible incline position. Excellent progression for building strength before advancing to weighted horizontal planks. The added load builds exceptional core strength.');

INSERT INTO garmin_exercises (exercise_category, exercise_name, type, tags, equipment, description)
VALUES ('PLANK', 'WEIGHTED_90_DEGREE_STATIC_HOLD', 'STRENGTH', '{core,abs,hip flexors,shoulders,isometric}', '{weight plates,ankle weights,weight vest}', 'L-sit or 90-degree hold with added weight - brutally difficult. Hold body at 90 degrees with weight added via vest, ankle weights, or held weight. This elite-level exercise builds exceptional core strength, hip flexor endurance, and shoulder stability under load. The added resistance makes an already brutal exercise even harder. Only for very advanced athletes. Builds extraordinary isometric strength.');

INSERT INTO garmin_exercises (exercise_category, exercise_name, type, tags, equipment, description)
VALUES ('PLANK', 'WEIGHTED_BEAR_CRAWL', 'STRENGTH', '{core,abs,shoulders,conditioning,full body}', '{weight vest}', 'Bear crawl with weight vest added for increased resistance. Crawl on hands and feet with knees hovering while wearing weighted vest. The added load significantly increases strength and conditioning demands. This brutal full-body exercise builds exceptional core stability, shoulder endurance, and work capacity. The weight makes every step more challenging. Elite conditioning exercise for athletes.');

INSERT INTO garmin_exercises (exercise_category, exercise_name, type, tags, equipment, description)
VALUES ('PLANK', 'WEIGHTED_CROSS_BODY_MOUNTAIN_CLIMBER', 'STRENGTH', '{core,abs,obliques,conditioning,cardio}', '{weight vest,ankle weights}', 'Cross-body mountain climbers with added weight via vest or ankle weights. Drive knee across body toward opposite elbow while wearing additional resistance. The added weight significantly increases oblique and cardiovascular demands. This challenging variation builds rotational core strength and conditioning under load. The weight makes each rep more demanding. Advanced conditioning exercise.');

INSERT INTO garmin_exercises (exercise_category, exercise_name, type, tags, equipment, description)
VALUES ('PLANK', 'WEIGHTED_ELBOW_PLANK_PIKE_JACKS', 'STRENGTH', '{core,abs,shoulders,hip flexors,conditioning}', '{weight vest}', 'Elbow plank pike jacks with weight vest added. From elbow plank, jump feet apart while piking hips, wearing vest. The added resistance significantly increases core and shoulder demands during this already challenging plyometric movement. Builds explosive core power under load. Elite-level exercise for advanced athletes. The weight adds significant difficulty to the dynamic movement.');

INSERT INTO garmin_exercises (exercise_category, exercise_name, type, tags, equipment, description)
VALUES ('PLANK', 'WEIGHTED_ELEVATED_FEET_PLANK', 'STRENGTH', '{core,abs,shoulders,isometric}', '{weight plates,weight vest}', 'Elevated feet plank with weight added - combining elevation and load. Feet on bench with weight plate on back or weight vest worn. This brutally difficult variation stacks multiple progression factors. The combination of elevation and weight creates maximum core and shoulder demands. Only for very advanced athletes. Builds extraordinary core strength and endurance.');

INSERT INTO garmin_exercises (exercise_category, exercise_name, type, tags, equipment, description)
VALUES ('PLANK', 'WEIGHTED_ELEVATOR_ABS', 'STRENGTH', '{core,abs}', '{weight plates,weight vest}', 'Plank elevator abs with weight added - pulsing hip movements with resistance. Small controlled hip movements up and down while wearing weight or holding plate. The added resistance makes the micro-movements significantly more challenging. Builds exceptional core endurance and time under tension. The weight increases the difficulty of maintaining constant core engagement.');

INSERT INTO garmin_exercises (exercise_category, exercise_name, type, tags, equipment, description)
VALUES ('PLANK', 'WEIGHTED_EXTENDED_PLANK', 'STRENGTH', '{core,abs,shoulders,isometric}', '{weight plates,weight vest}', 'Extended plank with weight added - THE ultimate plank challenge. Hands positioned forward with weight plate on back or vest worn. This combination of extended lever arm and added load creates maximum possible plank difficulty. Only for elite-level athletes. The stacked progression factors require extraordinary core and shoulder strength. Builds exceptional anti-extension strength.');

INSERT INTO garmin_exercises (exercise_category, exercise_name, type, tags, equipment, description)
VALUES ('PLANK', 'WEIGHTED_FULL_PLANK_PASSE_TWIST', 'STRENGTH', '{core,abs,obliques,hip flexors,balance}', '{weight vest,ankle weights}', 'Plank passe twist with added weight - dynamic movement with resistance. From plank, lift knee toward chest with rotation while wearing weight. The added resistance increases the difficulty of the complex movement pattern. Builds weighted multi-planar core strength. Advanced variation for building functional strength under load.');

INSERT INTO garmin_exercises (exercise_category, exercise_name, type, tags, equipment, description)
VALUES ('PLANK', 'WEIGHTED_INCHING_ELBOW_PLANK', 'STRENGTH', '{core,abs,shoulders}', '{weight plates,weight vest}', 'Inching elbow plank with weight added - dynamic movement with load. Inch forward and backward on forearms while wearing weight or holding plate. The added resistance significantly increases core and shoulder demands during the dynamic movement. Builds exceptional dynamic core strength and shoulder endurance under load. Advanced progression for inching planks.');

INSERT INTO garmin_exercises (exercise_category, exercise_name, type, tags, equipment, description)
VALUES ('PLANK', 'WEIGHTED_INCHWORM_TO_SIDE_PLANK', 'STRENGTH', '{core,abs,obliques,shoulders,hamstrings,full body}', '{weight vest,dumbbells}', 'Inchworm to side plank with weight vest or dumbbells held. Walk hands out with weight, rotate to side plank, return. This complex weighted movement builds exceptional total body strength and coordination. The added resistance increases all components of the movement. Elite full-body exercise combining multiple movement patterns under load.');

INSERT INTO garmin_exercises (exercise_category, exercise_name, type, tags, equipment, description)
VALUES ('PLANK', 'WEIGHTED_KNEELING_PLANK', 'STRENGTH', '{core,abs,shoulders,isometric}', '{weight plates,weight vest}', 'Kneeling plank with weight added - progressing the beginner variation. From knees with weight plate on back or vest worn. The added resistance builds strength while maintaining the accessible kneeling position. Excellent progression for those working toward weighted full planks. Builds foundational core strength under load.');

INSERT INTO garmin_exercises (exercise_category, exercise_name, type, tags, equipment, description)
VALUES ('PLANK', 'WEIGHTED_KNEELING_SIDE_PLANK_WITH_LEG_LIFT', 'STRENGTH', '{core,abs,obliques,hip abductors,balance}', '{weight vest,ankle weights}', 'Kneeling side plank with weighted leg lift. From kneeling side plank, lift top leg with ankle weights or while wearing vest. The added resistance increases hip abductor and oblique demands. This weighted progression builds lateral core and hip strength. Excellent for building strength while maintaining the accessible kneeling base.');

INSERT INTO garmin_exercises (exercise_category, exercise_name, type, tags, equipment, description)
VALUES ('PLANK', 'WEIGHTED_LATERAL_ROLL', 'STRENGTH', '{back,core,abs,obliques}', '{weight vest,dumbbells}', 'Lateral roll from plank to side plank with weight vest or dumbbells. Roll from front plank through side planks with added resistance. The weight significantly increases the rotational control and strength demands. Builds weighted multi-planar core strength and coordination. Advanced dynamic core exercise under load.');

INSERT INTO garmin_exercises (exercise_category, exercise_name, type, tags, equipment, description)
VALUES ('PLANK', 'WEIGHTED_LYING_REVERSE_PLANK', 'STRENGTH', '{glutes,hamstrings,lower back,shoulders,isometric}', '{weight plates,weight vest}', 'Reverse plank with weight added - typically plate on hips or vest worn. Face-up plank position with added resistance. The weight significantly increases posterior chain demands and shoulder stability requirements. Builds exceptional glute, hamstring, and lower back strength under load. Advanced progression for reverse planks.');

INSERT INTO garmin_exercises (exercise_category, exercise_name, type, tags, equipment, description)
VALUES ('PLANK', 'WEIGHTED_MEDICINE_BALL_MOUNTAIN_CLIMBER', 'STRENGTH', '{core,abs,shoulders,conditioning,cardio}', '{medicine ball,weight vest,ankle weights}', 'Mountain climbers on medicine ball with additional weight added. Hands on unstable ball, wearing vest or ankle weights. This brutally difficult combination stacks ball instability with added resistance. Builds elite-level core stability, shoulder control, and conditioning. The combination creates maximum challenge. Only for very advanced athletes.');

INSERT INTO garmin_exercises (exercise_category, exercise_name, type, tags, equipment, description)
VALUES ('PLANK', 'WEIGHTED_MODIFIED_MOUNTAIN_CLIMBER_AND_EXTENSION', 'STRENGTH', '{core,abs,hip flexors,glutes,conditioning}', '{weight vest,ankle weights}', 'Modified mountain climber with extension, weighted. Drive knee to chest then extend leg back with added weight. The resistance increases both the flexion and extension components. Builds weighted hip flexor and glute strength with core stability. Advanced variation for complete hip and core development under load.');

INSERT INTO garmin_exercises (exercise_category, exercise_name, type, tags, equipment, description)
VALUES ('PLANK', 'WEIGHTED_MOUNTAIN_CLIMBER', 'STRENGTH', '{core,abs,hip flexors,shoulders,conditioning,cardio}', '{weight vest,ankle weights}', 'Mountain climbers with weight vest or ankle weights added. Rapidly alternate driving knees to chest with added resistance. The weight significantly increases cardiovascular and muscular demands. Builds exceptional core conditioning and hip flexor endurance under load. Advanced progression for building weighted work capacity. The resistance makes each rep more challenging.');

INSERT INTO garmin_exercises (exercise_category, exercise_name, type, tags, equipment, description)
VALUES ('PLANK', 'WEIGHTED_MOUNTAIN_CLIMBER_ON_SLIDING_DISCS', 'STRENGTH', '{core,abs,hip flexors,shoulders}', '{sliding discs,weight vest,ankle weights}', 'Sliding disc mountain climbers with weight added. Feet on sliders, wearing vest or ankle weights. The combination of smooth sliding motion and added resistance creates exceptional core demands. Builds controlled core strength and hip flexor endurance under load. The continuous tension from sliding plus weight is brutally effective.');

INSERT INTO garmin_exercises (exercise_category, exercise_name, type, tags, equipment, description)
VALUES ('PLANK', 'WEIGHTED_MOUNTAIN_CLIMBER_WITH_FEET_ON_BOSU_BALL', 'STRENGTH', '{core,abs,hip flexors,shoulders,balance,conditioning}', '{bosu ball,weight vest,ankle weights}', 'BOSU mountain climbers with weight added - ultimate mountain climber challenge. Feet on unstable BOSU, wearing vest or ankle weights. This extreme combination stacks instability and resistance. Builds elite-level core stability, balance, and conditioning. The combination creates maximum difficulty. Only for very advanced athletes.');

INSERT INTO garmin_exercises (exercise_category, exercise_name, type, tags, equipment, description)
VALUES ('PLANK', 'WEIGHTED_MOUNTAIN_CLIMBER_WITH_HANDS_ON_BENCH', 'STRENGTH', '{core,abs,hip flexors,shoulders,conditioning}', '{bench,weight vest,ankle weights}', 'Incline mountain climbers with weight added. Hands elevated on bench, wearing vest or ankle weights. The incline makes the movement more accessible while the weight maintains intensity. Excellent weighted progression for those working toward full weighted mountain climbers. Builds core conditioning under load.');

INSERT INTO garmin_exercises (exercise_category, exercise_name, type, tags, equipment, description)
VALUES ('PLANK', 'WEIGHTED_MOUNTAIN_CLIMBER_WITH_HANDS_ON_SWISS_BALL', 'STRENGTH', '{core,abs,hip flexors,shoulders,balance,conditioning}', '{swiss ball,weight vest,ankle weights}', 'Swiss ball mountain climbers with weight - the ultimate combination. Hands on unstable ball, wearing vest or ankle weights. This extreme variation stacks ball instability with added resistance. Builds extraordinary core stability, shoulder control, and conditioning. Only for elite athletes. The combination creates maximum possible difficulty.');

INSERT INTO garmin_exercises (exercise_category, exercise_name, type, tags, equipment, description)
VALUES ('PLANK', 'WEIGHTED_PLANK', 'STRENGTH', '{core,abs,shoulders,isometric}', '{weight plates,weight vest}', 'Standard plank with weight plate on back or weight vest worn - THE weighted plank progression. Add progressive resistance to build maximum core strength. This fundamental weighted variation allows systematic strength progression beyond bodyweight. The added load builds exceptional core strength and endurance. Essential progression for advanced core training. Start with lighter weight and progress gradually.');

INSERT INTO garmin_exercises (exercise_category, exercise_name, type, tags, equipment, description)
VALUES ('PLANK', 'WEIGHTED_PLANK_JACKS_WITH_FEET_ON_SLIDING_DISCS', 'STRENGTH', '{core,abs,hip abductors,hip adductors,shoulders,conditioning}', '{sliding discs,weight vest}', 'Sliding plank jacks with weight vest added. Slide feet apart and together while wearing weight. The combination of smooth sliding motion and added resistance builds exceptional core and hip strength. The continuous tension plus weight creates maximum difficulty. Advanced variation for building weighted dynamic core strength.');

INSERT INTO garmin_exercises (exercise_category, exercise_name, type, tags, equipment, description)
VALUES ('PLANK', 'WEIGHTED_PLANK_KNEE_TWIST', 'STRENGTH', '{core,abs,obliques,hip flexors}', '{weight vest,ankle weights}', 'Plank knee twist with added weight - knee to opposite elbow with resistance. Drive knee across body with rotation while wearing weight. The added resistance increases oblique and hip flexor demands. Builds weighted rotational core strength. Advanced progression for dynamic oblique development under load.');

INSERT INTO garmin_exercises (exercise_category, exercise_name, type, tags, equipment, description)
VALUES ('PLANK', 'WEIGHTED_PLANK_PIKE_JUMPS', 'STRENGTH', '{core,abs,hip flexors,shoulders,plyometric,conditioning}', '{weight vest}', 'Explosive plank pike jumps with weight vest - brutal plyometric core exercise. Jump feet toward hands while piking hips, wearing vest. The added resistance significantly increases the explosive power and conditioning demands. Builds weighted explosive core power. Elite-level plyometric exercise. The weight makes each rep dramatically harder.');

INSERT INTO garmin_exercises (exercise_category, exercise_name, type, tags, equipment, description)
VALUES ('PLANK', 'WEIGHTED_PLANK_PIKES', 'STRENGTH', '{core,abs,hip flexors,shoulders,hamstrings}', '{weight vest}', 'Controlled plank pikes with weight vest added. Pike hips up toward ceiling with added resistance. The weight significantly increases core and shoulder demands during the dynamic movement. Builds weighted dynamic core control and hip flexor strength. The controlled non-jumping version with added load.');

INSERT INTO garmin_exercises (exercise_category, exercise_name, type, tags, equipment, description)
VALUES ('PLANK', 'WEIGHTED_PLANK_TO_STAND_UP', 'STRENGTH', '{core,abs,legs,full body,functional}', '{weight vest,dumbbells}', 'Complex plank-to-standing transition with weight added. From plank, transition to standing while wearing vest or holding dumbbells. The added resistance increases the difficulty of the full-body movement pattern. Builds weighted functional strength and coordination. Advanced progression for total body control under load.');

INSERT INTO garmin_exercises (exercise_category, exercise_name, type, tags, equipment, description)
VALUES ('PLANK', 'WEIGHTED_PLANK_WITH_ARM_RAISE', 'STRENGTH', '{core,abs,shoulders,balance,anti-rotation}', '{weight plates,weight vest,dumbbells}', 'Plank with one arm raise and weight added. Lift arm forward while wearing vest or holding weight in other hand. The combination of unilateral movement and added resistance creates maximum anti-rotation demands. Builds extraordinary weighted core stability. Elite-level weighted plank progression.');

INSERT INTO garmin_exercises (exercise_category, exercise_name, type, tags, equipment, description)
VALUES ('PLANK', 'WEIGHTED_PLANK_WITH_KNEE_TO_ELBOW', 'STRENGTH', '{core,abs,obliques,hip flexors}', '{weight vest,ankle weights}', 'Plank knee-to-elbow with weight added. Bring knee to same-side elbow while wearing vest or ankle weights. The added resistance increases oblique and hip flexor demands during the dynamic movement. Builds weighted lateral core strength. Advanced progression for dynamic core control under load.');

INSERT INTO garmin_exercises (exercise_category, exercise_name, type, tags, equipment, description)
VALUES ('PLANK', 'WEIGHTED_PLANK_WITH_OBLIQUE_CRUNCH', 'STRENGTH', '{core,abs,obliques,hip flexors}', '{weight vest,ankle weights}', 'Side plank oblique crunch with weight added. Crunch knee toward chest while in side plank, wearing weight. The added resistance intensifies oblique engagement and hip flexor demands. Builds weighted oblique strength and definition. Advanced progression for lateral core development under load.');

INSERT INTO garmin_exercises (exercise_category, exercise_name, type, tags, equipment, description)
VALUES ('PLANK', 'WEIGHTED_PLYOMETRIC_SIDE_PLANK', 'STRENGTH', '{core,abs,obliques,shoulders,plyometric,power}', '{weight vest}', 'Explosive side plank jumps with weight vest - ultimate plyometric side plank. Jump explosively from side to side while wearing vest. This extreme variation builds weighted explosive rotational power. Only for elite athletes. The combination of plyometrics and weight creates maximum oblique power development.');

INSERT INTO garmin_exercises (exercise_category, exercise_name, type, tags, equipment, description)
VALUES ('PLANK', 'WEIGHTED_ROLLING_SIDE_PLANK', 'STRENGTH', '{core,abs,obliques,shoulders}', '{weight vest,dumbbells}', 'Rolling side planks with weight added - flow from side to side with resistance. Roll smoothly between side planks while wearing vest or holding dumbbells. The weight increases rotational control demands. Builds weighted multi-planar core strength. Advanced dynamic exercise for rotational power under load.');

INSERT INTO garmin_exercises (exercise_category, exercise_name, type, tags, equipment, description)
VALUES ('PLANK', 'WEIGHTED_SIDE_KICK_PLANK', 'STRENGTH', '{core,abs,obliques,hip abductors,balance}', '{weight vest,ankle weights}', 'Side plank with weighted leg kicks. From side plank, perform kicks with top leg while wearing vest or ankle weights. The added resistance increases hip and oblique demands. Builds weighted lateral core and hip strength with dynamic movement. Advanced combination exercise under load.');

INSERT INTO garmin_exercises (exercise_category, exercise_name, type, tags, equipment, description)
VALUES ('PLANK', 'WEIGHTED_SIDE_PLANK', 'STRENGTH', '{core,abs,obliques,shoulders,isometric}', '{weight plates,weight vest,dumbbells}', 'Side plank with weight added - THE weighted side plank progression. Hold weight plate on hip, wear vest, or hold dumbbell at top. This fundamental weighted lateral core exercise allows progressive overload for oblique development. Essential for building maximum lateral core strength. Start with lighter weight and progress gradually.');

INSERT INTO garmin_exercises (exercise_category, exercise_name, type, tags, equipment, description)
VALUES ('PLANK', 'WEIGHTED_SIDE_PLANK_AND_ROW', 'STRENGTH', '{core,abs,obliques,back,shoulders,anti-rotation}', '{dumbbells}', 'Side plank with weighted dumbbell row - THE ultimate weighted side plank challenge. Hold heavier dumbbell in top hand and row while in side plank. This brutally difficult combination builds maximum weighted oblique strength and anti-rotation control. Elite-level exercise combining lateral core stability with heavy pulling. Only for advanced athletes.');

INSERT INTO garmin_exercises (exercise_category, exercise_name, type, tags, equipment, description)
VALUES ('PLANK', 'WEIGHTED_SIDE_PLANK_LIFT', 'STRENGTH', '{core,abs,obliques,hips}', '{weight plates,weight vest,dumbbells}', 'Weighted side plank hip dips and lifts. Lower and lift hips while wearing weight or holding plate. The added resistance dramatically increases oblique endurance demands during the dynamic movement. Builds weighted lateral core strength through motion. Advanced progression for oblique hypertrophy under load.');

INSERT INTO garmin_exercises (exercise_category, exercise_name, type, tags, equipment, description)
VALUES ('PLANK', 'WEIGHTED_SIDE_PLANK_WITH_ELBOW_ON_BOSU_BALL', 'STRENGTH', '{core,abs,obliques,shoulders,balance,isometric}', '{bosu ball,weight plates,weight vest,dumbbells}', 'Weighted BOSU side plank - combining instability and resistance. Elbow on BOSU, holding weight or wearing vest. This extreme combination stacks ball instability with added load. Only for elite athletes. Builds extraordinary weighted lateral core stability. The combination creates maximum lateral core challenge.');

INSERT INTO garmin_exercises (exercise_category, exercise_name, type, tags, equipment, description)
VALUES ('PLANK', 'WEIGHTED_SIDE_PLANK_WITH_FEET_ON_BENCH', 'STRENGTH', '{core,abs,obliques,shoulders,isometric}', '{bench,weight plates,weight vest,dumbbells}', 'Weighted elevated side plank - feet on bench with added resistance. This brutal combination stacks elevation and weight for maximum oblique challenge. The elevated position plus weight creates extraordinary demands. Only for very advanced athletes. Builds elite-level weighted lateral core strength.');

INSERT INTO garmin_exercises (exercise_category, exercise_name, type, tags, equipment, description)
VALUES ('PLANK', 'WEIGHTED_SIDE_PLANK_WITH_KNEE_CIRCLE', 'STRENGTH', '{core,abs,obliques,hip flexors,hip mobility}', '{weight vest,ankle weights}', 'Side plank with weighted knee circles. Draw circles with top knee while wearing weight. The added resistance increases core stability demands during the hip mobility work. Builds weighted lateral core strength and hip flexibility simultaneously. Advanced combination of stability and mobility under load.');

INSERT INTO garmin_exercises (exercise_category, exercise_name, type, tags, equipment, description)
VALUES ('PLANK', 'WEIGHTED_SIDE_PLANK_WITH_KNEE_TUCK', 'STRENGTH', '{core,abs,obliques,hip flexors}', '{weight vest,ankle weights}', 'Side plank with weighted knee tuck. Tuck top knee toward chest while wearing weight. The added resistance increases hip flexor and oblique demands. Builds weighted lateral core strength with dynamic leg movement. Advanced progression for functional core development under load.');

INSERT INTO garmin_exercises (exercise_category, exercise_name, type, tags, equipment, description)
VALUES ('PLANK', 'WEIGHTED_SIDE_PLANK_WITH_LEG_LIFT', 'STRENGTH', '{core,abs,obliques,hip abductors,balance,isometric}', '{weight plates,weight vest,dumbbells,ankle weights}', 'Weighted side plank with leg lift - THE ultimate side plank challenge. Lift top leg while holding weight or wearing vest and ankle weights. This maximum difficulty variation stacks multiple progression factors. Builds elite-level weighted lateral core and hip strength. Only for very advanced athletes.');

INSERT INTO garmin_exercises (exercise_category, exercise_name, type, tags, equipment, description)
VALUES ('PLANK', 'WEIGHTED_SIDE_PLANK_WITH_REACH_UNDER', 'STRENGTH', '{core,abs,obliques,shoulders,rotation}', '{weight vest,dumbbells}', 'Side plank reach-under with weight - thread arm under body with added resistance. Hold dumbbell in top hand and thread under while wearing vest. The weighted rotational movement dramatically increases oblique and anti-rotation demands. Builds weighted dynamic lateral core strength. Advanced rotational core exercise under load.');

INSERT INTO garmin_exercises (exercise_category, exercise_name, type, tags, equipment, description)
VALUES ('PLANK', 'WEIGHTED_SINGLE_LEG_ELEVATED_FEET_PLANK', 'STRENGTH', '{core,abs,glutes,anti-rotation,unilateral,isometric}', '{bench,box,weight plates,weight vest}', 'The ultimate weighted plank - single-leg elevated with added resistance. One foot on bench, other leg lifted, wearing vest or holding plate. This extreme variation stacks elevation, unilateral, and weight. Only for elite athletes. Builds extraordinary weighted anti-rotation strength. Maximum plank difficulty.');

INSERT INTO garmin_exercises (exercise_category, exercise_name, type, tags, equipment, description)
VALUES ('PLANK', 'WEIGHTED_SINGLE_LEG_FLEX_AND_EXTEND', 'STRENGTH', '{core,abs,hip flexors,glutes,anti-rotation,unilateral}', '{weight vest,ankle weights}', 'Weighted single-leg plank flex and extend. Tuck knee to chest then extend leg back while wearing weight. The added resistance increases hip flexor, glute, and core demands during the unilateral movement. Builds weighted single-leg control and anti-rotation strength. Advanced unilateral progression under load.');

INSERT INTO garmin_exercises (exercise_category, exercise_name, type, tags, equipment, description)
VALUES ('PLANK', 'WEIGHTED_SINGLE_LEG_SIDE_PLANK', 'STRENGTH', '{core,abs,obliques,hip abductors,balance,unilateral,isometric}', '{weight plates,weight vest,dumbbells,ankle weights}', 'The ultimate weighted side plank - single-leg with added resistance. One foot only, holding weight or wearing vest. This maximum difficulty variation is only for elite athletes. Builds extraordinary weighted lateral core control. The combination of single-leg and weight creates supreme challenge.');

INSERT INTO garmin_exercises (exercise_category, exercise_name, type, tags, equipment, description)
VALUES ('PLANK', 'WEIGHTED_SPIDERMAN_PLANK', 'STRENGTH', '{core,abs,obliques,hip flexors,hip mobility}', '{weight vest,ankle weights}', 'Weighted spiderman plank - knee to elbow outside the body with added resistance. Drive knee up and out toward elbow while wearing weight. The added resistance increases hip mobility and core stability demands. Builds weighted functional hip and core strength. Advanced dynamic core exercise under load.');

INSERT INTO garmin_exercises (exercise_category, exercise_name, type, tags, equipment, description)
VALUES ('PLANK', 'WEIGHTED_STRAIGHT_ARM_PLANK', 'STRENGTH', '{core,abs,shoulders,isometric}', '{weight plates,weight vest}', 'High plank (straight arms) with weight added. Support on hands with weight plate on back or vest worn. The weighted straight-arm position increases shoulder stability demands significantly. Builds weighted shoulder and core strength. Essential for weighted push-up progressions. Start light and progress gradually.');

INSERT INTO garmin_exercises (exercise_category, exercise_name, type, tags, equipment, description)
VALUES ('PLANK', 'WEIGHTED_STRAIGHT_ARM_PLANK_WITH_SHOULDER_TOUCH', 'STRENGTH', '{shoulders,core,abs,anti-rotation}', '{weight vest}', 'Weighted shoulder taps - alternating shoulder touches with weight vest. Tap opposite shoulder alternately while wearing vest. The added resistance dramatically increases anti-rotation and shoulder stability demands. Builds weighted dynamic core control. Advanced anti-rotation exercise under load. Keep hips square throughout.');

INSERT INTO garmin_exercises (exercise_category, exercise_name, type, tags, equipment, description)
VALUES ('PLANK', 'WEIGHTED_SWISS_BALL_PLANK', 'STRENGTH', '{core,abs,shoulders,balance,isometric}', '{swiss ball,weight plates,weight vest}', 'Weighted swiss ball plank - combining instability and resistance. Forearms on ball, wearing vest or holding weight. This extreme combination stacks ball instability with added load. Only for very advanced athletes. Builds elite-level weighted core stability on unstable surface. Maximum core challenge.');

INSERT INTO garmin_exercises (exercise_category, exercise_name, type, tags, equipment, description)
VALUES ('PLANK', 'WEIGHTED_SWISS_BALL_PLANK_LEG_LIFT', 'STRENGTH', '{core,abs,glutes,shoulders,balance,anti-rotation}', '{swiss ball,weight plates,weight vest,ankle weights}', 'Weighted swiss ball plank with leg lift - ultimate combination. Forearms on ball, lift leg, wear vest and ankle weights. This supreme variation stacks instability, unilateral, and weight. Only for elite athletes. Builds extraordinary weighted core control on unstable surface.');

INSERT INTO garmin_exercises (exercise_category, exercise_name, type, tags, equipment, description)
VALUES ('PLANK', 'WEIGHTED_SWISS_BALL_PLANK_LEG_LIFT_AND_HOLD', 'STRENGTH', '{core,abs,glutes,shoulders,balance,anti-rotation,isometric}', '{swiss ball,weight plates,weight vest,ankle weights}', 'Weighted swiss ball plank with sustained single-leg hold - the ultimate isometric core challenge. Forearms on ball, lift and hold one leg elevated with vest and ankle weights. This brutal isometric variation combines ball instability with prolonged asymmetric loading and added resistance. The extended hold time builds extraordinary endurance and control under weighted conditions. Only for elite athletes. Builds supreme weighted core stability on unstable surface.');

INSERT INTO garmin_exercises (exercise_category, exercise_name, type, tags, equipment, description)
VALUES ('PLANK', 'WEIGHTED_SWISS_BALL_PLANK_WITH_FEET_ON_BENCH', 'STRENGTH', '{core,abs,shoulders,balance,isometric}', '{swiss ball,bench,weight plates,weight vest}', 'The absolute ultimate weighted plank - forearms on swiss ball with feet elevated on bench plus added weight. This extreme variation combines ball instability with elevated feet positioning and external resistance. Creates maximum possible core and shoulder demands through triple difficulty stack. Only for elite-level athletes with exceptional strength and control. The combination of unstable base, elevated feet, and weight is supremely difficult. Builds extraordinary weighted core and shoulder control.');

INSERT INTO garmin_exercises (exercise_category, exercise_name, type, tags, equipment, description)
VALUES ('PLANK', 'WEIGHTED_SWISS_BALL_PRONE_JACKKNIFE', 'STRENGTH', '{core,abs,hip flexors,shoulders}', '{swiss ball,weight vest,ankle weights}', 'Weighted swiss ball jackknife - dynamic pike movement with added resistance. Hands on floor, shins on ball, pike hips up pulling ball forward while wearing vest or ankle weights. This advanced weighted core exercise builds exceptional abdominal strength and hip flexor power under load. The ball rolling adds instability throughout the weighted movement. The added resistance makes an already challenging exercise brutally difficult. Elite-level dynamic core exercise for building weighted power.');

INSERT INTO garmin_exercises (exercise_category, exercise_name, type, tags, equipment, description)
VALUES ('PLANK', 'WEIGHTED_SWISS_BALL_SIDE_PLANK', 'STRENGTH', '{core,abs,obliques,shoulders,balance,isometric}', '{swiss ball,weight plates,weight vest,dumbbells}', 'Weighted side plank with forearm on unstable swiss ball. Forearm on ball while holding weight or wearing vest. This extreme weighted variation combines lateral instability with added resistance. The ball creates tremendous lateral instability, dramatically increasing oblique and shoulder demands under load. Requires constant balance adjustments while supporting added weight. Elite weighted side plank progression. Only for very advanced athletes. Builds extraordinary weighted lateral core stability.');

INSERT INTO garmin_exercises (exercise_category, exercise_name, type, tags, equipment, description)
VALUES ('PLANK', 'WEIGHTED_T_STABILIZATION', 'STRENGTH', '{core,abs,obliques,shoulders,rotation}', '{dumbbells,weight vest}', 'Weighted T-stabilization - plank to side plank rotation with added resistance. From straight-arm plank, rotate to side plank reaching weighted arm toward ceiling. Hold dumbbell in rotating arm or wear weight vest. This dynamic weighted rotational exercise builds exceptional core stability, shoulder mobility, and coordination under load. The T position with weight requires tremendous balance and oblique control. Elite weighted rotational strength exercise. The added resistance makes the rotation significantly more challenging.');

INSERT INTO garmin_exercises (exercise_category, exercise_name, type, tags, equipment, description)
VALUES ('PLANK', 'WEIGHTED_THREE_WAY_PLANK', 'STRENGTH', '{core,abs,obliques,shoulders,isometric}', '{weight plates,weight vest}', 'Weighted three-way plank sequence - holding front, right side, and left side planks with added resistance. Hold each weighted position for designated time while wearing vest or holding plate. This comprehensive weighted core workout targets abs, obliques, and shoulders from multiple angles under load. The tri-planar approach with weight builds complete core strength and endurance. Excellent for building total weighted core endurance and stability. The added resistance makes each position significantly more challenging.');

INSERT INTO garmin_exercises (exercise_category, exercise_name, type, tags, equipment, description)
VALUES ('PLANK', 'WEIGHTED_TOWEL_PLANK_AND_KNEE_IN', 'STRENGTH', '{core,abs,hip flexors,shoulders}', '{towels,weight vest,ankle weights}', 'Weighted towel plank knee-in - sliding knee tuck with added resistance. Feet on towels on smooth floor, slide both knees toward chest while wearing vest or ankle weights. This dynamic weighted core exercise combines the benefits of mountain climbers with controlled sliding motion and added load. The towels create smooth, continuous tension while the weight increases strength demands. Builds exceptional weighted core strength and hip flexor endurance. The combination of sliding motion and weight is brutally effective.');

INSERT INTO garmin_exercises (exercise_category, exercise_name, type, tags, equipment, description)
VALUES ('PLANK', 'WEIGHTED_TURKISH_GET_UP_TO_SIDE_PLANK', 'STRENGTH', '{core,abs,obliques,shoulders,full body,functional}', '{kettlebell,dumbbells}', 'Weighted partial Turkish get-up stopping at side plank position with heavier load. From lying with heavier weight overhead, rise to side plank position. This functional weighted movement combines the Turkish get-up with side plank hold under significant load. Builds exceptional total body strength, weighted shoulder stability, and loaded core control. The complex movement pattern with heavy weight challenges coordination and multi-planar strength. Elite functional strength exercise for building weighted movement quality.');

INSERT INTO garmin_exercises (exercise_category, exercise_name, type, tags, equipment, description)
VALUES ('PLANK', 'WEIGHTED_TWO_POINT_PLANK', 'STRENGTH', '{core,abs,glutes,shoulders,balance,anti-rotation,isometric}', '{weight plates,weight vest}', 'The ultimate weighted plank - two-point support with added resistance. Lift opposite arm and leg simultaneously while wearing vest or holding plate. This maximum difficulty weighted variation stacks two-point base, added weight, and anti-rotation demands. Requires extraordinary weighted core control and glute engagement. Only for elite-level athletes. Builds supreme weighted stability and coordination under load. The combination creates maximum possible plank difficulty.');

INSERT INTO garmin_exercises (exercise_category, exercise_name, type, tags, equipment, description)
VALUES ('PLANK', 'WEIGHTED_WIDE_STANCE_PLANK_WITH_DIAGONAL_ARM_LIFT', 'STRENGTH', '{core,abs,shoulders,balance,anti-rotation}', '{weight vest,dumbbells}', 'Weighted wide stance plank with diagonal arm lift - wider base with added resistance. Feet wide apart, lift arm diagonally while wearing vest or holding dumbbell. The wide stance provides more stability than narrow base but the weighted arm lift still creates anti-rotation challenge. This progression builds weighted shoulder stability and core control. The diagonal reach pattern engages core differently than straight-forward raises. Excellent weighted variation for building rotational control under load.');

INSERT INTO garmin_exercises (exercise_category, exercise_name, type, tags, equipment, description)
VALUES ('PLANK', 'WEIGHTED_WIDE_STANCE_PLANK_WITH_DIAGONAL_LEG_LIFT', 'STRENGTH', '{core,abs,glutes,balance,anti-rotation}', '{weight vest,ankle weights}', 'Weighted wide stance plank with diagonal leg lift - wider base with weighted leg raise. Feet wide apart, lift leg diagonally while wearing vest or ankle weights. The wide stance provides stability base but weighted leg lift creates anti-rotation and glute demands. This progression builds weighted posterior chain and core strength. The diagonal lift pattern engages glutes and core differently than straight raises. Excellent for weighted hip and core development.');

INSERT INTO garmin_exercises (exercise_category, exercise_name, type, tags, equipment, description)
VALUES ('PLANK', 'WEIGHTED_WIDE_STANCE_PLANK_WITH_LEG_LIFT', 'STRENGTH', '{core,abs,glutes,balance,anti-rotation}', '{weight vest,ankle weights}', 'Weighted wide stance plank with straight leg lift - wider stable base with added resistance. Feet wide apart, lift one leg straight back while wearing vest or ankle weights. The wide stance provides stability while the weighted leg lift challenges glutes and core. This accessible weighted progression builds posterior chain and anti-rotation strength. Excellent for those progressing toward more advanced weighted single-leg planks. The wider base makes the weighted movement more manageable.');

INSERT INTO garmin_exercises (exercise_category, exercise_name, type, tags, equipment, description)
VALUES ('PLANK', 'WIDE_STANCE_PLANK_WITH_DIAGONAL_ARM_LIFT', 'STRENGTH', '{core,abs,shoulders,balance,anti-rotation,isometric}', '{bodyweight}', 'Wide stance plank with diagonal arm lift - feet wider apart for more stable base. Feet wide, lift arm diagonally across body. The wide stance reduces instability compared to narrow base, making the arm lift more accessible. This regression allows focus on shoulder stability and anti-rotation control without extreme balance demands. Excellent progression toward standard single-arm planks. The diagonal reach pattern challenges core control.');

INSERT INTO garmin_exercises (exercise_category, exercise_name, type, tags, equipment, description)
VALUES ('PLANK', 'WIDE_STANCE_PLANK_WITH_DIAGONAL_LEG_LIFT', 'STRENGTH', '{core,abs,glutes,balance,anti-rotation,isometric}', '{bodyweight}', 'Wide stance plank with diagonal leg lift - feet wider for stable base, lift leg diagonally. Feet wide apart, raise leg at diagonal angle. The wide stance provides more stability than narrow base while still challenging glute and core engagement. This accessible progression builds posterior chain strength and anti-rotation control. Excellent for learning single-leg plank mechanics. The diagonal lift pattern engages glutes and core effectively.');

INSERT INTO garmin_exercises (exercise_category, exercise_name, type, tags, equipment, description)
VALUES ('PLANK', 'WIDE_STANCE_PLANK_WITH_LEG_LIFT', 'STRENGTH', '{core,abs,glutes,balance,anti-rotation,isometric}', '{bodyweight}', 'Wide stance plank with straight leg lift - feet wider for more stable base. Feet wide apart, lift one leg straight back. The wide stance reduces instability compared to narrow base, making the leg lift more accessible. This regression allows focus on glute engagement and anti-rotation control without extreme balance demands. Excellent progression toward standard single-leg planks. The wider base builds foundational strength and stability.');

INSERT INTO garmin_exercises (exercise_category, exercise_name, type, tags, equipment, description)
VALUES ('PLANK', 'WIDE_STANCE_PLANK_WITH_OPPOSITE_ARM_AND_LEG_LIFT', 'STRENGTH', '{core,abs,glutes,shoulders,balance,anti-rotation,isometric}', '{bodyweight}', 'Wide stance plank with opposite arm and leg lift - bird dog position from wider base. Feet wide apart, lift opposite arm and leg simultaneously. The wide stance provides more stability than narrow base while still creating significant anti-rotation challenge. This accessible two-point plank progression builds total body coordination and core control. Excellent stepping stone toward standard two-point plank. The wider base makes the complex movement more manageable while maintaining core engagement.');